heeya15/Algorithm_Study

- 220711/안영원_programmers_단체사진 찍기.java
조합가능한 모든 경우의 수를 찾은 다음에 해당 경우의 수가 문제의 조건과 일치하는지 확인하고
일치하다면 answer를 증가시켜서 찾는 완탐 방식을 사용해서 풀이
> 220711 안영원 프로그래머스 단체사진 찍기 풀이

- 220711/김광희_programmers_단체사진찍기.java
( 문제 풀이 )
* 순열을 활용하여 카카오 프렌즈가 설 수 있는 모든 경우의 수를 구한 뒤, 
* < 매개변수로 주어진 " data의 원소 다섯 글자로 구성된 문자열을 활용 ">하여
* 주어진 조건을 모두 만족하는 경우 결과 변수 answer을 +1로 해 줌.
> 220711 김광희 프로그래머스 단체사진 찍기 풀이

- 220713/강소현_programmers_신고 결과 받기.java
<풀이>
1. 아래 형태로 문제 풀이 시작
HashMap<String, Integer> id_map = new HashMap<>(); // <유저가 신고한 ID, 신고된 횟수 저장>
HashMap<String, HashSet<String>> report_map = new HashMap<>(); // <유저가 신고한 ID, 유저 ID>
2. 유저가 신고한 ID가 존재하면 신고 ID 넣음
3. value로 key를 찾아서 신고 횟수가 k개 이상인지를 파악하고 신고 횟수를 저장
> 220713 강소현 프로그래머스 신고 결과 받기 풀이

- 220713/김광희_programmers_신고 결과 받기.java
( 문제 풀이 ) 
-  1. "2가지 HashMap을 이용"하여 하나는 유저id index 용도, 또 다른 하나는 각 유저별 자신을 신고한 유저를 저장하기 위해 사용
-  2. 2가지중 하나의 HashMap의 Value를 set으로 사용
-> 문제에서 동일한 유저에 대한 신고 횟수는 1회로 처리 지문을 보고 -> Value를 set으로 적용할 생각.
-  3. 신고 기록을 한다. -> 신고자 id에 누가 신고했는지를 기록
-  4. 유저별 자신을 "신고한 사람이 k번 이상" 이라면 메일을 보내줌
ex) 해당하는 유저id HashMap의 index 순서에 맞는 answer값을 증가시켜준다. answer[map.get(name)]++;
> 220713 김광희 프로그래머스 신고 결과 받기 풀이

- 220713/박동준_programmers_신고 결과 받기.py
해당 사람을 신고 한 사람의 list를 value
신고 받은 사람을 key 로 가지는 dict 생성 후,
이를 이용하여 k 이상의 값을 가지는 신고받은 사람이 있다면,
value list 에 있는 신고 한 사람의 index 값을 추적하여 +1 을 해주면 풀 수 있는 문제였습니다.
> 220713 박동준 프로그래머스 신고 결과 받기 풀이

- 220718/박동준_boj_2615.py
dfs 라고 생각했습니다.
핵심 풀이법은
1. 가장 왼쪽에 있는 바둑알이기 때문에 방향벡터를 (오른쪽, 아래쪽, 오른쪽 대각아래, 오른쪽 대각 위) 로 설정해야하는점,
2. 하지만 여섯 알 이상이 연속적으로 놓인 경우에는 이긴 것이 아니다. 라는 문제의 전제조건입니다.
bfs 에서 총 count가 5가 되었는지 확인 후, 양끝점에 같은 바둑돌이 있다면 오목이 아닌것을 체크 해 주면 됩니다.
> 220718  박동준 백준 2615 풀이

- 220720/안영원_boj_14890_경사로.java
가로 세로를 각각 확인하면서
경사로를 놓을 수 있으면 놓고 길이 완료되면 추가하는 방식으로 계산.
> 220720 안영원 백준 14890 경사로 풀이

- 220720/김광희_boj_14890_경사로.java
( 문제 풀이 ) 
- 시뮬레이션, 구현 알고리즘.
- 일반 배열, 거꾸로 배열을 활용하여 하나의 함수에, 동일 매개변수 개수로 처리하도록 함.
- 가로, 세로 방향을 각각 확인하면서 주어진 조건에 따라 처리하고
- 경사로를 놓을 수 있으면 경사로의 개수 1씩 추가하여 해결
> 220720 김광희 백준 14890 경사로 풀이

- 220720/박동준_boj_14890_경사로.py
가로세로 분할 탐색,
조건 분기를 list 길이 탐색 시도하던 도중 실패 후
처음부터 다시 진행중..
> 220720 박동준 백준 14890 경사로 풀이

- 220720/강소현_boj_14890_경사로.java
- 220721/강소현_programmers_부족한 금액 계산하기.java
<풀이>
놀이기구 탈 횟수를 for문 돌려서 놀이기구 이용료를 구한 후 가진 돈에서 뺀다.
> 220721 강소현 프로그래머스 부족한 금액 계산하기 풀이

- 220721/장예찬_programmers_부족한 금액 계산.py
> 220721 장예찬 프로그래머스 부족한 금액 계산하기 풀이

- 220721/김광희_programmers_부족한 금액 계산하기.java
( 문제 풀이 )
- 놀이기구 이용 횟수 만큼 for 반복문을 도는대, 놀이 기구 이용료를 (이용 횟수 * 놀이기구 이용료)를 하여 누적 요금 금액을 sum 변수에 저장
- 최종 적으로 3항 연산자를 이용하여 놀이기구를 count번 타게 되면 현재 자신이 가지고 있는 금액에서 모자라면 
( 누적 요금 금액 - 처음 가지고 있는 금액을 해주고) 부족하지 않다면 0을 결과 변수에 저장하여 해결
> 220721 김광희 프로그래머스 부족한 금액 계산하기 풀이

- 220721/장예찬_programmers_부족한 금액 계산.py
Reverts heeya15/Algorithm_Study#28
> Revert "220721 장예찬 프로그래머스 부족한 금액 계산하기 풀이"

- 220725/강소현_programmers_문자열 압축.java
1. 반복하는 비교 문자열 길이는 [문자열 길이 / 2 + 1]
2. 타켓 문자열과 비교 문자열을 두어 카운트 하는 방식으로 품
> 220725 강소현 프로그래머스 문자열 압축 풀이

- 220721/박동준_programmers_부족한 금액 계산하기.py
- 220725/박동준_programmers_문자열 압축.py
문자열을 slice 하여 비교하고 이에 따라 더해주면 되는 간단한 문제
마지막 끝의 문자열의 경우 비교 대상이 없어 더해지지않는다는점을 놓쳤었음
> 220725 박동준 프로그래머스 문자열 압축 풀이

- 220725/김광희_programmers_문자열 압축.java
( 문제 풀이 )
- 바깥쪽 for문은  s.length() / 2 만큼 반복 
ex) 예를들어 문자열 길이 8인경우 주어진 문자열을 5로 잘라서 어떻게든 압축을 하려고 해도 할 수가없기 때문. 
- 안 쪽 for문은 "문자열을 i개 단위로 잘라가며" 압축하기 위해 다시 한번 for문 사용
- 현재 타겟과 다음 문자가 같은 경우 "압축 정도 증가", 
- 그렇지 않다면 압축된 정도에 따라 문자열을 StringBuilder에 추가하고 < 타겟 패턴을 다음 문자로 변경 > 
- 안 쪽 for문이 끝나고 아직 압축이 안된 문자가 있는 것을 StringBuilder에 타겟 문자를 추가
- answer의 값과 "현재 StringBuilder에 압축된 문자열의 길이 중" < 더 작은 수를 answer 값으로 할당 >
> 220725 김광희 프로그래머스 문자열 압축 풀이

- 220727/박동준_boj_16174_점프왕쩰리.py
배열 탐색 문제
주요 문제 풀이 point
1. 이동 가능 거리가 0인 지점에 갔을때, 도착불가
2. 이동벡터를 해당 arr의 값에 곱해준다.
> 220727 박동준 백준 16174 점프왕 쩰리 풀이

- 0727/안영원_boj_16174_점프왕_쩰리.java
DFS로 하다가 BFS로 선회
0이상 100이하여서 0일 때 무한반복이 될까봐 0을 스킵하는 코드를 넣었지만
방문체크를 하면 굳이 의미없는 일이었다.
방문..체크.. 메...모....
> 220727 안영원 백준 16174 점프왕 쩰리 풀이

- 220727/김광희_boj_16174_점프왕 쩰리.java
( 문제 풀이 ) 
- BFS를 이용하여 "오른쪽 또는 아래로만" 해당 칸에 쓰여져 있는 수 만큼만 이동하여 탐색
- 가장 오른쪽 즉 '-1'이 쓰여져 있는 칸에 도착하면 true, 도착하지 못하면 false로 반환하게 해결.
> 220727 김광희 백준 16174 점프왕 쩰리 풀이

- 220728/강소현_boj_2239_스도쿠.java
예전에 많이 풀어봤던 문제라 그때 풀었던 방식을 상기시켜 그대로 풀었습니다.
- 스도쿠 규칙은 9x9와 3x3에 1~9까지 각각 숫자 하나씩만 들어가야 함.
- 그래서 9x9, 3x3을 나눠서 숫자 체크를 했음.
- 열이 스도쿠 사이즈인 N에 도달했을 때, 더 이상 탐색할 게 없으므로 다음 행으로 넘어가서 다시 탐색
- 행의 끝에 도달하면 체크가 됐다는 것을 의미하며 스도쿠 탐색을 끝냄.
> 220728 강소현 백준 2239 스도쿠 풀이

- 220728/김광희_boj_2239_스토쿠.java
( 문제 풀이 ) 
- 백 트래킹을 활용하여 열을 증가시키면서 보드 좌표 값이 0일 경우 1~ 9 숫자에 대해 유효성 체크를 해준다
- 유효성 체크는 행, 열, 3 * 3 좌표에 중복된 값이 있는지 확인 -> 계속 잘 채워나가다가 맞지 않는 경우를 생각하여  현재 호출된 값을 0으로 초기화 하고 return 하여 이전 빈칸 부터 재귀 함수를 다시 호출.
- 열이 9가 되면 행을 하나씩 증가 시켜 재귀 호출
- 마지막 행 8까지 다 수행하고 x가 9가 될 경우 스토쿠 퍼즐 출력 -> 여기서 한 번만 출력 하게 System.exit(0) 함수 사용.. 해주지 않으닌깐 모든 좌표의 값이 0일때 계속 출력되어 출력 초과가 되었음...
> 220728 김광희 백준 2239 스도쿠 풀이

- 220728/안영원_boj_2239_스도쿠.java
> 220728 안영원 백준 2239 스도쿠 풀이

- 220729/박동준_boj_2239_스도쿠.py
0이 있는 좌표를 구한다.
해당 좌표에 들어갈 수 있는 수를 찾는다.
행, 열, 박스에 들어갈 수 있는 숫자를 찾고, 들어갈 수 있는 숫자면 arr에 값을 넣은 후 재귀 호출
재귀가 retrun 되었을때는 다시 0으로 변경
하나씩 무식하게 채웠습니다.
> 220728 박동준 백준 2239 스도쿠 풀이

- 220727/장예찬_boj_16174.py
- 220728/장예찬_boj_2239.py
풀이
1. 2차원 리스트 입력을 받음, visited 배열 초기화
2. 방문했던 곳은 재방문 X
3. bfs로 풀이
> 220727 장예찬 백준 16174 점프왕 쩰리 풀이

- 220801/장예찬_programmers_[1차] 뉴스 클러스터링.py
문제 풀이
1. alphabet인 두 글자 리스트 추출
2. 딕셔너리를 활용한 문자별 개수 세기
3. 중복이 허용된 교집합과 합집합 계산
전체 시간 복잡도: O(n)
> 220801 장예찬 프로그래머스 [1차] 뉴스 클러스터링 풀이

- 220803/장예찬_programmers_모음사전.py
풀이
1. 0개부터 5개까지 선택한 중복순열 결과 리스트를 저장.
2. 정렬 (n log n 소모)
3. 탐색으로 인덱스를 출력 (만약 이진 탐색 하면 약간 시간 줄어듬)
시간복잡도: O(n log n)
> 220803 장예찬 프로그래머스 모음사전 풀이

- 220803/강소현_programmers_모음사전.java
1. 부분집합(x) --> 중복순열(o)으로 A, E, I, O, U로 만들 수 있는 모든 단어를 만들어서 list에 저장
2. Collection.sort를 이용해 정렬
3. 효율성 구릴 거 같음
> 220803 강소현 프로그래머스 모음사전 풀이

- 220803/박동준_programmers_모음사전.py
1. dfs 원리로 재귀시킨다.
2. 재귀할때 a,e,i,o,u 로 만들어둔 배열을 순서대로 탐색
3. 이 순서로 탐색시 depth == 5 레벨일때부터 모음 순서대로 끝배열이 바뀜,
4. 대신 각 재귀가 발생하기 전 spell을 추가시켜줌
5. 재귀호출된 함수가 종료되면 추가되었던 스펠을 제거
이후 입력된 word의 index를 탐색하고 +1을 해주면 찾던값이나옴
이렇게 할 수 있던 이유는 n < 5 인 무지성 재귀를 돌려도 시간초과가 날 수 없음
> 220803 박동준 프로그래머스 모음사전 풀이

- 220803/안영원_programmers_모음사전.java
완전탐색이라 적혀있어서.. 다 탐색해야하는 줄 알았더니..
규칙이 있더라이다...
각 단어 위치별로 횟수를 구한다.
첫 번째 단어가 바뀌는 횟수는 781회 이후에 오고 그 다음은 156, 31, 6, 1 순서다.
규칙을 통해 해당 단어가 몇 번째인지 계산이 가능하다.
> 220803 안영원 프로그래머스 모음사전 풀이

- 220804/박동준_boj_20208_진우의 민트초코우유.py
1. n 이 모두 10 보다 작기때문에 백트래킹이 가능함.
2. bfs로 하기엔 모든 탐색이 오히려 복잡해짐을 고려, mint의 좌표와 집의 좌표를 받아옴
3. 이때 각 민트를 먹었을때, 집으로 갈 수 있으면 그때마다 카운트를 체킹함
4. 반복문을 돌면서 내가 방문하지 않은 민트가, 현재 내 채력으로 갈 수 있으면 방문처리
- 이때 중요한점은, 해당 좌표로 갔을 때 움직이게 된 좌표와 집간의 거리를 함께 넘겨줌 그렇게 함으로서 3번의 과정을 거칠 수 있음
5. 처음에는 종료조건이 필요없다고 느꼇으나, 모든 음료를 다 먹었을때 종료를 시켜주면 됨
함수의 인자가 의미하는것
x좌표,y좌표,hp, 집까지의거리, 이때까지먹은 민트우유 갯수
> 220804 박동준 백준 20208 진우의 민트초코우유 풀이

- 220804/강소현_boj_20208_진우의 민트초코우유.java
우유 좌표를 리스트에 담고 탐색했습니다. boolean 처리를 해서 이미 마신 민트초코우유 좌표에 다시 안 가도록 했습니다.  처음에 boolean 처리를 안 해줘서 사단이 났었습니다... 그리고 거리 계산을 한 후에 지금 체력으로 갈 수 있으면 재귀를 돌려 count 시키는 방식으로 구현했습니다. 이후 집으로 돌아갈 때는 현재 좌표와 집 좌표를 통해 거리를 구하고 집에 무사히 도착하면 진우가 먹은 민트초코우유 최대 개수를 반환 시켰습니다.
> 220804 강소현 백준 20208 진우의 민트초코우유 풀이

- 220804/안영원_boj_20208_진우의 민트초코우유.java
처음에 푼 방식으로는 DFS를 이용해서 하나씩 다 움직여보면서
집에 도착하면 값을 갱신하는 방식으로 했으나 실패
우유가 최대 10개라서 리스트에 담아서 우유를 찾아가는 방식으로 변경
우유를 찾기 전에 현재 위치에서 집으로 갈 수 있다면 max를 변경하고 갈 수 없다면 재귀를 종료하는 방식으로 했는데 실패
우유를 찾고 나서 해당 위치에서 집으로 갈 수 있다면 추가적으로 boolean을 이용해 표시해주고 재귀를 돌림
재귀 시작 부분에서 집으로 온 친구라면 max 값을 변경하고 재귀 종료 방식으로 성공
> 220804 안영원 백준 20208 진우의 민트초코우유 풀이

- 220804/장예찬_boj_20208_진우의 민트초코우유.py
[풀이]
1. 지도와 지도에서 우유 위치, 내 위치를 저장
2. 우유별로 다른 우유와의 거리 dict 저장 (최대 100번 반복)
3. dfs로 백트래킹해서 문제 풀이
지난 Failed 커밋도 PyPy3에선 통과함....
Python이 쑤레기
이건 진짜 사소하게 계산 시간 복잡도를 줄인 버전
> 220804 장예찬 백준 20208 진우의 민트초코우유 풀이

- 220804/김광희_boj_20208_진우의 민트초코우유.java
( 문제 풀이 )
1. 진우의 집 좌표는 (houseX,houseY) 변수에 저장 
민트 초코우유 좌표 정보는 ArrayList<int[]> mint_milk 에 담아둔다.
2. 민트 초코우유 좌표 정보 개수 만큼 -> numbers, visited 배열 사이즈 초기화
3. 민트 초코우유가 있는 좌표 정보를 "순열로 구한 ArrayList 인덱스"에 따라 사용한다.
4. 현 좌표에서 다음 민트 초코우유 까지의 거리와, 진우 집에서 다음 민트 초코우유 까지의 거리를 구한다.
그 후 현 좌표에서 다음 민트 초코유 까지의 거리가  -> 진우 hp 보다 작거나 같다면 마시러 갈 수 있고, 마시러 갈 수 있는 민트 초코우유의 개수(count)증가.
< 집에서 다음 민트 초코우유 까지의 거리 > 또한 "hp 보다 작거나 같다면" 
마시러 갈 수 있는 민트 초코우유의 개수(count)와 최종 결과(result)를 비교하여 더 큰 값으로 갱신 시켜준다.
> 220804 김광희 백준 20208 진우의 민트초코우유 풀이

- 220808/안영원_boj_12761_돌다리.java
동규는 주미가 보고 싶단다.
내 손수 만나게 해주었다.
문제에서 8가지의 이동가능한 경우가 있다.
+1, -1, +A, -A, +B, -B, *A, *B
최소 횟수를 찾는 것이기 때문에
BFS를 사용했다.
처음엔 8가지 경우를 다 넣고 돌려버렸더니 검색하는데 5분은 더 걸렸다.
그래서 뭐가 문제지 했더니 이미 찾아본 곳을 또 찾고 있길래
얼마나 보고싶길래 봤던 곳을 또 보고 있니 싶어서
방문 처리를 통해 봤던 곳은 안 살펴봐도 되게 했다.
그랬더니 잘 만나더라
행복해라..
> 220808 안영원 백준 12761 돌다리 풀이

- 220808/강소현_boj_12761_돌다리.java
동규는 8가지 방법으로 움직일 수 있다. for문 돌려 조건식을 주려고 했었는데 코드가 좀 깔끔했으면 좋겠어서 ` int[] arr = new int[8] ` 배열을 생성하여 8가지 방법으로 움직일 수 있게 했다. 처음에는 동규가 움직일 때 방문처리를 하지 않았다. 그러니 메모리 초과가 났다. 이후 방문 처리까지 해서 현 코드로 작성했다.
> 220808 강소현 백준 12761 돌다리 풀이

- 220808/김광희_boj_12761_돌다리.java
( 문제 풀이 )
(1). bfs를 수행하는대 큐에는 < 동규의 현재 위치 값을 > 넣어준다.
(2). < 주어진 8가지 방법 중 사용하여 이동 할 수 있다면 > < 이동 횟수를 stones 배열에 저장 >하고 
큐에 동규가 이동한 현재 위치 값을 저장해 줌
(3). 방문 했던 좌표는 배열 값이 0이 아닌 경우에 해당해서 [ 따로 방문 체크 배열을 쓰지 않음 ]
(4). 최종 적으로 위와 같은 과정을 반복하다 "동규 현재 위치가 주미의 위치와 같을 경우" 
"해당 주미 위치 값인" stones 배열 인덱스에 최소 이동 횟수가 담겨 있어서 출력해 준다.
> 220808 김광희 백준 12761 돌다리 풀이 

- 220808/박동준_boj_12761_돌다리.py
x축이동 좌표를 잘 구분하면 된다.
하나 실수했던점은
for i in range(8):
nx = x + dx[i]
로 해서 문제를 풀었다는 점인데,
힘을 줘서 도약할때는 x*dx[i] 임을 간과하여 4연틀의 충격에 빠졌다.
이후 문제점을 발견하고 수정
이외에 사용 한 로직은
방문하는 위치에 전 좌표의 방문 횟수 + 1을 해주어
방문 처리 & 최소 거리를 함께 저장했다는 점이다.
끝!
> 220808 박동준 백준 12761 돌다리 풀이

- 220804/장예찬_boj_20208_진우의 민트초코우유.py
- 220808/장예찬_boj_12761_돌다리.py
풀이
BFS
왜 처음엔 동적 계획법으로 풀 수 있을 것처럼 보였을까
동적계획법이 안되는 반례를 찾고 조건을 더 추가하고 안되는 반례를 추가하고 반복하다 시간 오버
> 220808 장예찬 백준 12761 돌다리 풀이

- 220810/장예찬_boj_20056_마법사 상어와 파이어볼.py
풀이과정 
그냥 구현문제라 풀라는대로 풀었어요. 
파이어볼 이동
파이오볼 체크
> 220810 장예찬 백준 20056 마법사 상어와 파이어볼 풀이

- 220811/장예찬_boj_15683_감시.py
풀이
구현문제임
1. 카메라가 바라보는 방향의 좌표 변화량을 카메라 별로 지정했다.
2. 카메라의 위치와 종류를 저장했다.
3.  이럴거면 그냥 볼록거울이나 하나 설치해서 카메라 세우지 카메라 별로 직접 바라보는 방향을 중복순열이라 생각하고 따라가 보았다.
4. 이전 배열 상태를 저장(메모이제이션)하게 하기 위해 슬라이싱을 이용했다.
5. 그러면 머리는 안 좋지만 기억력은 좋은지 예전 카메라 방향을 불러와 모든 경우를 체크할 수 있다.
6. 모든 카메라를 방향을 지정해서 따라가 봤다면 안 보이는 곳을 체크해서 개수를 센다
7. 최소 값을 갱신한다.
> 220811 장예찬 백준 15683 감시 풀이

- 220810/강소현_boj_20056_마법사 상어와 파이어볼.java
- 220811/강소현_boj_15683_감시.java
문제가 어렵네요......내일 다시 풀겠습니다..
지금 파이어볼 이동조차도 제대로 못 시킨 느낌.
> 220810 강소현 백준 20056 마법사 상어와 파이어볼 풀이

- 220810/김광희_boj_20056_마법사 상어와 파이어볼.java
- 220811/김광희_boj_15683_감시.java
( 문제 풀이 )
1. cctv 개수만큼 중복 순열을 구한다
2. 사무실 정보를 copy_Map 2차원 배열에 복사한다.
3. 해당 탐색 (중복 순열) 방향으로 각 번호 cctv 방법의 화살표 방향 개수에 맞추어 탐색하여 이동
4. 사각 지대 개수를 세어준 다음, 여러 방법 중 사각 지대의 "최소" 크기를 Min 변수에 저장.
> 220811 김광희 백준 15683 감시 풀이

- 220811/안영원_boj_15683_감시.java
일단 실패
재귀를 통해 모든 CCTV 방향에 대한 결과를 찾아서
전부 확인하였는데
무언가를 빼먹은게 틀림없다.. 실패..
> 220811 안영원 백준 15683 감시 풀이

- 220810/박동준_boj_20056_마법사 상어와 파이어볼.py
- 220811/박동준_boj_15683_감시.py
1. 파이어볼을 이동시킨다.
- 이때 중요한점은 이동하는 좌표가 index 값을 넘어가면 다시 0번으로  연결되어있다는점을 주의해야한다.
2. 이동 후 이동한 파이어볼이 한 지점에 2개 이상으로 있으면 주어진 조건에 따라 파이어볼을 나누어준다.
- 주의할 점 : 분리시킨 후 이동시키면 안됨, 분리가 된 후 다음 이동 때 4방향으로 파이어볼이 뻗어나감
> 220810 박동준 백준 20056 마법사 상어와 파이어볼 & 15683 감시 풀이

- 220817/강소현_programmers_수식 최대화.java
> 220817 강소현 프로그래머스 수식 최대화 풀이

- 220810/안영원_boj_20056_마법사_상어와_파이어.java
- 220817/안영원_programmers_수식 최대화.java
- 220818/안영원_programmers_피로도.java
순열을 통해서 경우의 수를 찾는다.
찾은 경우의 수가 던전을 돌 수 있는지 확인한다.
이를 통해 몇 개의 던전을 돌 수 있는지 체크
> 220817 안영원 프로그래머스 피로도 풀이

- 220818/박동준_programmers_피로도.py
1. 갈 수 있는 경우의 순서가 있는 조합을 만든다.
2. 이 조합을 통해 나온 순서의 index 던전을 돌며 피로도 계산하고 갈 수 있는 곳이면 피로도를 감소시킨다.
3. 끝!
> 220818 박동준 프로그래머스 피로도 풀이

- 220818/김광희_programmers_피로도.java
( 문제 풀이 )  
1. 순열을 활용하여 던전을 탐험하는 순서 인덱스를 구한다.
2. 현재 피로도가 최소 필요 피로도보다 크거나 같다면 < 탐험할수 있는 던전의 수를 증가 > 및
< 현재 피로도를 > 던전 탐험하고 나서 < 소모 피로도를 빼준다 >.
3. 그 후 탐험할 수 있는 < 최대 던전 수를 max_dungeon_count에 반영 > 시켜준다.
> 220817 김광희 프로그래머스 피로도 풀이

- 220818/장예찬_programmers_피로도.py
9시에 문제를 에너지 모으기를 풀어버려서
10시에 풀기 시작함
ㅠㅠ
그냥 순열 문제 푸는 방식으로 품
> 220818 장예찬 프로그래머스 피로도 풀이

- 220822/강소현_boj_16198_에너지 모으기.java
- 재귀를 활용하여 풀었습니다.
- 첫번째와 마지막 에너지 구슬은 고를 수 없다는 조건을 통해 기저 조건을 `count == N-2` 로 조건을 줬습니다.
- 이후 list에 담은 구슬 에너지 값을 조건에 맞게 구하고 i번째 구슬을 제거한 뒤 재귀를 돌렸습니다.
> 220822 강소현 백준 16198 에너지 모으기 풀이

- 220822/박동준_boj_16198_에너지 모으기.py
1. n <10 이기 때문에 무지성 백트래킹
2. 배열의 특정 인덱스 값 제거하기전 i 번째 구슬을 선택했다면 i-1 ,i +1 번째 무게를 곱해서 num에 더해줌
3. 배열에서 i번째 인덱스 값 제거 후 재귀호출
4. 재귀가 종료되면, 다시 i번째 인덱스에 해당 값을 넣어주고 num 역시 더했던 값 만큼 빼줌
5. 끝
> 220822 박동준 백준 16198 에너지 모으기 풀이

- 220822/김광희_boj_16198_에너지 모으기.java
( 문제 풀이 )
1. 에너지를 모으는 방법을 그대로 적용하여 구현
2. dfs를 통하여 해당 i번째 값 구슬 무게를 제거하고, 모을 수 있는 에너지 양을 누적(energy)한다.
3. 만약 N-2 깊이 만큼 에너지 양을 누적하였을 경우, 모을 수 있는 에너지 양(result)이 "새로 구한 energy 에너지 양" 보다 작다면 
< 더 큰 에너지 양으로 갱신 > 해 준다.
4. 그 후, 다시 list에 사용했던 에너지를 원래 있던 index 위치에 넣어준다.
이러한 2 ~ 4번 과정을 반복하여 해결.
> 220822 김광희 백준 16198 에너지 모으기 풀이

- 220822/장예찬_boj_16987_계란으로 계란치기.py
풀이 방법
완전 탐색 구현 문제임
왼쪽부터 자기 자신이 아닌 계란을 모두 한 번 치는 경우를 재귀로 계산하면 됨
오답 원인
조합을 이용해서 풀려고 했으나 실패
완전 탐색 문제의 일종인 것 같은데 머리가 정리가 안됨
> 220822 장예찬 백준 16987 계란으로 계란치기 풀이

- 220824/안영원_programmers_두 큐 합 같게 만들기.java
풀이를 열심히 고민했다.
큐 길이가 길어서 단순하게 찾는 방법 말고 다른 방법이 있을거라고 한 30분 고민했는데 생각이 안나서 그냥 단순하게 풀기로 했다.
근데 통과함 ㅎ.ㅎ
큐 문제이기 때문에 큐에 주어진 배열을 넣고 푸는 방식을 선택하였다.
문제에서 Long Type을 쓰길 권유해서 사용했다.
주어진 수를 큐에 넣으면서 합을 체크해서 합이 2로 나누어지지 않는다면 문제를 풀 수 없기에 예외 처리를 하고
단순하게 큐1과 큐2 중 합이 큰 곳을 찾아 뺴고 다른 큐에 넣게끔 하였다.
반복문을 언제까지 돌리면서 찾아야할지 고민했는데 해당 부분은 질문하기 게시판을 통해 힌트를 얻었다.
해당 게시판에 아래와 같이 적혀있었다.
```
length * 2가 안되는 경우 example로 간단히 말로만 써놓겠습니다..! 길이가 5인 queue1과 queue2에서 유일한 답이 queue1의 2,3번째가 한 큐에만 들어가있는 경우..
0~3 (queue1) --> (queue2)(4스탭) & 0~6 (queue2) --> (queue1)(7스탭) 이경우 11만큼의 스탭이 필요하네요.
```
그래서 length * 3이 넘어가면 break 되고 값을 찾지 못한다고 결론내렸다.
> 220824 안영원 프로그래머스 두 큐 합 같게 만들기 풀이

- 220824/박동준_programmers_두 큐 합 같게 만들기.py
1. 처음에는 무지성 백트랙킹 시도했다. 근데 범위를 뒤늦게 보고 이런 빠가야로! 를 외치며 전부 지웠다.
2. sum을 이용하여 while문을 계속 순환시켰다. 시간초과가 났다 여기서부터 울면서 풀었다.
3. 초기 코드는 각 값을 비교할때마다, sum(q1) > sum(q2) 와 같이 계속 배열들의 합을 구해줬다. 이게 원인 1 이였다.
4. 내부에서 값을 비교하고 배열을 변경시켜줄때 pop(0)를 사용했다. 이게 시간 복잡도가 O(n)이라서 시간이 초과된 것이였따.
5. 비교값은 while문 전에 미리 한번 값을 더해주고, 비교한 후 deque를 통해 O(1)로 제일 앞의 배열 값을 빼고 더해줬다.
6. 겨우겨우 풀었다. 눈물이났다.
> 220824 박동준 프로그래머스 두 큐 합 같게 만들기 풀이

- 220825/강소현_programmers_기능개발.java
`(100% - 작업 진도) / 작업 속도` 을 list에 담아서 비교했으며 list에 담긴 `(100% - 작업 진도) / 작업 속도` 를 비교하여 max 값을 갱신하면서 특정 날에 몇개의 작업이 배포가 가능한지 구현했습니다.
> 220825 강소현 프로그래머스 기능개발 풀이

- 220825/안영원_programmers_기능개발.java
각 기능이 배포 가능해지는 날짜를 계산해서 큐에 넣어준다.
우선순위가 높은 기능이 뒷 기능보다 이 후에 개발 된다면 뒷 기능이 같이 배포되기에 해당 내용을 while을 이용해서 찾고 값을 더해줌.
그렇지 않고 우선 순위가 높은 기능이 개발 가능 날짜도 빠르다면 바로 list에 담아준다.
이렇게 풀었다.. !
> 220825 안영원 프로그래머스 기능개발 풀이

- 220825/김광희_programmers_기능개발.java
( 문제 풀이 ) -> 생각 흐름대로 풀음...
1. 각 progresses 원소별 작업 후 배포 일 수를 success라는 ArrayList에 추가
2. 첫 번째 작업 후 배포일 수를 꺼내온 뒤, 두 번째 작업 후 배포일 수와 비교하여 
만약 첫 번째 작업 후 배포일 수가 < 두 번째 작업 후 배포일 수 > 보다 크거나 같을경우
첫 번째 작업은 아직기능이 완성된 상태가 아니기 때문에 두 번째 작업은 첫 번째 작업과 같이 배포된다.
따라서 기능 배포의 수 count 변수를 증가한다.
3. 만약 그 반대라면 현재 까지 누적된 "배포의 수를" answer 이라는 ArrayList에 추가하고 
배포의 수는 1로 초기화, 다음 몇일 뒤 배포 가능한지를 진행 중의 작업으로 셋팅해 준다. 
그 후 2번 ~3번 과정을 반복 한 뒤 남은 배포에대한 몇개의 기능을 마저 answer 이라는 ArrayList에 추가
> 220825 김광희 프로그래머스 기능개발 풀이

- 220825/박동준_programmers_기능개발.py
1. 반복문을 돌립니다.
2. num을 통해 이미 100이 넘어서 지나온 배열이면 반복문에서 순회하지 않게 해줍니다 --> 범위설정용
3. 일단 하루치 다 더해줌
4. cnt 설정
5. num을 기준으로 반복문 시작 100을 넘었으면 시작점 증가, cnt 증가
6. 한번이라도 100을 넘지 않은 값이 있으면 break
7. num이 progresses길이만큼 되면 중지
8. cnt 가 0이 아니라면 answer에 추가
입니다.
> 220825 박동준 프로그래머스 기능개발 풀이

- 220829/안영원_programmers_오픈채팅방.java
해쉬맵을 사용했다. (Key: 아이디, Value: 닉네임)
Enter를 만나면 맵에 입력해주고
Change를 만나면 맵에 있는 걸 지우고 다시 넣어주는 방식을 사용(그냥 value를 지우고 입력해도 됬긴했을듯)
그런 다음에 다시 record를 탐색하면서 닉네임으로 채팅 로그를 기록해주었다.
> 220829 안영원 프로그래머스 오픈채팅방 풀이

- 220825/장예찬_programmers_기능개발.py
풀이방법
1. 큐에 남은 걸리는 시간을 넣는다.
2. 계산한다.
> 220825 장예찬 프로그래머스 기능개발 풀이

- 220829/김광희_programmers_오픈채팅방.java
( 문제 풀이 )
1. 채팅방에 들어온 경우와, 나간 경우를 ArrayList의 String 배열에 넣어준다.
2. HashMap을 활용하여 key는 user_id, value는 nickname으로 사용하였다. 
ex) key : uid4567  value : Prodo 가 HashMap에 값이 있는 상태에서 
< 동일한 key : uid4567 가 > 다른 닉네임 "Ryan으로 들어올 경우" 해당 key에 해당하는 "value가 Ryan으로 변경" 됨
즉 {key : uid4567,  value : Ryan}
3. 들어오거나, 나간 경우의 기록이 담긴 문자열 배열을 list에서 꺼내옴         
4. 해당 user_id를 통해 [ 닉네임을 ] HashMap 에서 찾음 
-> 최종적으로 방을 개설한 사람이 보게 되는 메시지 형태로 출력해 주기 위해서.
5. [ 최종적으로 들어온 기록 ]이라면 nickname + "님이 들어왔습니다." , [ 나간 기록 ]이라면  nickname + "님이 나갔습니다." 로 String 배열에 저장.
> 220829 김광희 프로그래머스 오픈채팅방 풀이

- 220829/장예찬_programmers_오픈채팅방.py
풀이방법
1. dictionary 를 만든다
2. 순수 아이디와 입퇴장 정보를 저장. 마지막 아이디의 닉네임 정보를 저장
3. 아이디에 맞춰 정보를 반환
> 220829 장예찬 프로그래머스 오픈채팅방 풀이 

- 220831/장예찬_programmers_성격 유형 검사하기.py
풀이 방법
1. dict을 사용해서 카운트
2. 방향을 알고 있는 리스트 지정
3. 리스트 원소를 이용해 각 dict에 해당하는 유형 점수 계산
4. 대소에 맞게 출력
> 220831 장예찬 프로그래머스 성격 유형 검사하기 풀이

- 220831/안영원_programmers_성격 유형 검사하기.java
HashMap을 이용해서 각 성격 유형의 점수를 계산하고
단순 IF-ELSE를 이용해서 점수가 더 높은 성격 유형을 표시하게끔 하였습니다.
IF-ELSE 말고 더 깔끔한 방법이 있을 거 같은데 생각이 안나용 히히..
> 220831 안영원 프로그래머스 성격 유형 검사하기 풀이

- 220831/강소현_programmers_성격 유형 검사하기.java
풀었던 문제라 다시 풀었습니다.
- `String[] type = {"R", "T", "C", "F", "J", "M", "A", "N"};` 타입을 배열로 두고 map에 담았습니다.
- survey 배열에 있는 문자를 substring으로 쪼갠 뒤, 점수 계산을 했습니다.
- 이후 지표 별로 점수가 높은 순으로 정렬했습니다.
ex) 
✅ 라이언형(R) 점수 < 튜브형(T) 점수 → 튜브형(T) 문자열 저장
✅ 라이언형(R) 점수 == 튜브형(T) 점수 → 알파벳 사전순으로 빠른 알파벳 문자열 저장
✅ 라이언형(R) 점수 > 튜브형(T) 점수 → 라이언형(R) 문자열 저장
> 220831 강소현 프로그래머스 성격 유형 검사하기 풀이

- 220831/박동준_programmers_성격 유형 검사하기.py
1. 점수값을 입력해줄 딕셔너리 생성
2. choice의 입력값을 index로 가지고, 그 입력 index에 따라 점수 할당하는 리스트
3. 각 유형별로 묶여있는 문자열 리스트 생성
4. 이후 각 survey와 choices의 index 값을 기준으로 반복문을 통해 dic 에 점수 누적
5. 유형별 문자열 리스트를 정렬시켜주고, 각 문제의 조건에 따라 answer에 값 누적
끝~!
> 220831 박동준 프로그래머스 성격 유형 검사하기 풀이

- 220831/김광희_programmers_성격 유형 검사하기.java
( 문제 풀이 )
1. 각 지표에 대한 성격 유형을 HashMap에 key로 해당 성격 유형의 점수를 value로 사용
2. 선택한 선택지 (choices[i])에 따라 해당 성격 유형에 점수를 추가 시켜줌
3. 각 지표에서 더 높은 점수를 받은 유형을 검사자의 성격 유형으로 지정
4. 만약 각 성격 유형 점수가 같을 경우 두 성격 유형 중 사전순으로 빠른 성격 유형을 검사자의 성격 유형이라 판단하여 해결.
> 220831 김광희 프로그래머스 성격 유형 검사하기 풀이

- 220905/강소현_boj_17144_미세먼지 안녕!.java
- 미세먼지 확산, 위쪽 공기 청정기, 아래쪽 공기청정기 분리해서 구현
- 시계 방향, 반시계 방향 배열은 기본적으로 생성한 4방탐색 배열 인덱스 값 기준으로 시계방향은 `우 - 하 - 좌 - 상` , 반시계 방향은 `우 - 상 - 좌 - 하` 으로 배열 생성한다.
- 공기 청정기 바람 순환은 공기 청정기 바로 오른쪽 위치에서 시작하므로 위쪽 공기청정기와 아래쪽 공기청정기 둘 다 air[i][1]에서 시작한다. 공기청정기는 벽을 만날 때 까지 계속 탐색해야하기 때문에 while문을 돌렸다.
- `바람이 불면 미세먼지가 바람의 방향대로 모두 한 칸씩 이동` 조건때문에 공기청정기 바람 순환시킬 때, 미리 배열을 복사한 뒤 이동한 배열에 복사한 배열 값을 넣어가면서 순환시켰다.
> 220905 강소현 백준 17144 미세먼지 안녕! 풀이

- 220905/박동준_boj_17144_미세먼지 안녕.py
문제에 주어진대로 구현한다.
주요 로직
1. spread --> 확산의 경우 정보를 옮길 배열을 생성 한다. 이때, 값을 다 수정한 후, 공기청정기 위치를 복사하지 않아서 틀렸었다.
2. up ,down --> 이전의 값을 저장하고, 공기청정기에서 나오는 0 을 시작으로 한칸씩 옮긴다. 다음 가야하는 좌표가 범위를 벗어났다면 방향을 바꿔준다
> 220905 박동준 백준 17144 미세먼지 안녕! 풀이

- 220901/장예찬_boj_20055_컨베이어 벨트 위의 로봇.py
풀이 방법
1. 컨베이너 enter, out을 인덱스 번호로 지정해서 번호만 이동
2. 각 단계 별로 0을 카운팅
3. K 개 이상이 되면 break 후 단계 출력
Pypy3에서 정답, Python3에서 오답(시간초과)
다른 시간 복잡도 좋은 풀이를 보면 나눗셈 연산 대신 deque를 이용함
> 220901 장예찬 백준 컨베이어 벨트 위의 로봇 풀이

- 220905/김광희_boj_17144_미세먼지 안녕!.java
( 문제 풀이 )
1. 집 정보를 map 배열에 저장하고, 공기 청정기가 위치한 행을 Aircleaner 변수에 저장 
-> 가장 왼쪽 열에 위치하다고 문제 지문에 있기 때문에 "행만" 저장.
2. 미세먼지가 있는 위치를 "큐(dust_location)"에 담는다
3. 미세먼지를 확산 시킨다. 
-> 미세먼지 양이 5보다 작은 경우는 어차피 확산이 0이 되어서 가지 치기 해줌.
4. 공기청정기를 작동한다. 
-> 위쪽 공기 청정기 부터 반시계 방향, 오른쪽 공기 청정기는 시계 방향으로 순환하게 작동
-> 따라서 바람이 불 때 미세먼지가 바람의 방향대로 모두 한 칸씩 이동
-> 여기서 방향 회전 부분을 가장 마지막 회전 방향 부터 당겨주는 방식으로 진행 하였다.
즉, 이 문제는 주어진 순서대로 구현하여 해결하면 된다.
> 220905 김광희 백준 17144 미세먼지 안녕! 풀이

- 220907/안영원_boj_13397_구간 나누기 2.java
이분 탐색 힌트를 들어서 조금 풀이를 쉽게 찾은 느낌
아마 몰랐으면 나누는 구간의 수에 집중해서 풀지 못했을 것 같다.
이분탐색의 기준값으로 구간의 최대값을 지정한다.
left는 0, right는 배열의 최댓값으로 지정해서 mid 정하고
해당값으로 구간을 나누게 되면 구간이 몇 개 나오는지 탐색한다.
나온 구간의 수가 M보다 크다면 left를 늘려서 mid를 줄여주고
M보다 작거나 같다면 right를 줄여서 mid값을 키워주며 답을 찾아나간다.
코드에 주석넣음
> 220907 안영원 백준 13397 구간 나누기 2 풀이

- 220907/강소현_boj_13397_구간 나누기 2.java
- start = 0, end = 배열에서 가장 큰 값으로 정하여 탐색 / mid = (start + end) / 2
- 배열 전체를 탐색해서 최댓값, 최솟값을 갱신
- 해당 배열 최댓값과 최솟값을 찾고 `최댓값 - 최솟값`이 mid 보다 큰 값이라면 구간을 카운트하고 현재 인덱스 기준으로 max, min값 갱신
- 카운트 한 `구간의 개수 <= M개` 라면 result 변수에 mid 값을 갱신. 이후 `구간의 개수 == M` 이면 result 반환
> 220907 강소현 백준 13397 구간 나누기 2 풀이

- 220905/장예찬_boj_17144_미세먼지 안녕!.java
- 220905/장예찬_boj_17144_미세먼지 안녕!.py
풀이 방법
1. 사방 탐색으로 먼지 퍼트리기
2. 모서리 만날 때마다, 공청기 라인으로 도착할 때까지 외곽 돌려주기
> 220905 장예찬 백준 17144 미세먼지 안녕! 풀이

- 220907/김광희_boj_13397_구간 나누기 2.java
( 문제 풀이 )
1. left = 0, right = 배열에서 가장 큰 원소값으로 저장
2. 이진 탐색을 활용하여, 배열 전체를 탐색하면서 < 최댓값 최솟값을 구하고, 갱신 해서 구간의 수를 구한다.
3. 구간의 수가 M개 구간 보다 작거나 같다면 result 값을 갱신 및 오른쪽 기준을 mid -1 로 해준다
4. 구간의 수가 M개 구간 보다 크다면 왼쪽 기준을 mid + 1로 해준다.
5. left가 right 보다 크다면 while을 탈출하여 result 값을 출력해 준다.
> 220907 김광희 백준 13397 구간 나누기 2 풀이

- 220908/강소현_programmers_JadenCase 문자열 만들기.java
- 주어진 문자열 s 각 한글자씩 쪼개서 소문자로 변경 후 String 배열에 담는다.
- `현재 인덱스가 0` 이거나 `현재 인덱스 기준 이전 인덱스에 공백`이 존재하면 대문자로 변경 후 StringBuilder에 담는다. 그 외에는 소문자로 변경한 문자열을 그대로 StringBuilder에 담는다.
> 220908 강소현 프로그래머스 JadenCase 문자열 만들기 풀이

- 220908/안영원_programmers_JadenCase 문자열 만들기.java
한글자씩 탐색하면서 앞 글자가 공백일 때 대문자로 만들어주는 방식 사용
최적화 하기엔 너무 졸리다..
일단 풀었으니까 만족
> 220908 안영원 프로그래머스 JadenCase 문자열 만들기 풀이 

- 220908/김광희_programmers_JadenCase 문자열 만들기.java
( 문제 풀이 )
1. 매개변수로 주어진 문자열 s를 모두 소문자로 만들어준 것을 char 배열안에 각 원소별로 넣어준다.
2. isFirst라는 첫 문자 판별 상태 변수를 true로 초기화를 둔 뒤, 주어진 문자열을 가지고 만든 char 배열 길이 만큼 반복문 돌기
-> 첫 문자는 우선 대문자로 처리 하기 위해 isFirst 라는 첫 문자 판별 상태 변수 true로 초기화
3. 그 후, 공백을 만났을 경우 isFirst라는 상태변수가 true, 그렇지 않다면 false로 초기화 시킴.
-> 공백 다음에 글자를 대문자로 만들기 위해서 상태변수 true로 하고 그렇지 않으면 false로 다 소문자로 StringBuilder에 넣어준다.
4. 위 과정을 통하여 StringBuilder 에 바뀐 문자열을 출력.
> 220908 김광희 프로그래머스 JadenCase 문자열 만들기 풀이

- 220914/Lv3_코딩테스트공부.java
내일 마저 풀겠습니다.. 이제 문제 이해가 된거 같네요 ... 점화식 어캐 세우지...
> 220914 김광희 프로그래머스 코딩 테스트 공부 풀이

- 220908/장예찬_programmers_JadenCaase 문자열 만들기.py
1. 일부러 map과 split을 활용해서 최대한 for문의 N개수를 줄여보려고 노력함
2. 근데 결국 find 함수 때문에 O(N)이 되어버림
3. 추가적인 연산 덕분에 더 비효율적인 알고리즘이 됨
1. 전형적인 O(N) 풀이법
2. 코드가 짧고 추가적인 연산이 적음
> 220908 장예찬 프로그래머스 JadenCase 문자열 만들기 풀이

- 220915/장예찬_boj_1937_욕심쟁이 판다.py
[풀이과정]
1. dp를 이용해서 푼다.
2. dfs와 dp를 이용한 백트래킹?을 활용한다.
3. 문제는 python으로 푸니 RecursionError가 발생하여 pypy3를 이용하니 풀렸다.
> 220915 장예찬 백준 1937 욕심쟁이 판다 풀이

- 220915/안영원_boj_1937_욕심쟁이 판다.java
몰라서 풀이 확인해서 풀음
대충 예상한 것은 맞았음.
DFS로 모두 다 확인하면 시간이 오래걸리기 때문에 메모이제이션 사용해서 이미 방문한 곳에서는 추가로 탐색하지 않게끔 설정 해야함
> 220915 안영원 백준 1937 욕심쟁이 판다 풀이

- 220919/박동준_programmers_방금그곡.py
1. #을 어떻게 처리하느냐 가 관건이다.
2. 우선 곡의 시간과 멜로디를 알기 위해서 반복문을 시작한다.
3. 각각 노래의 멜로디를 list로 변환시킬 것이다.
4.  노래의 멜로디를 index 값으로 반복할때 # 이 있다면  마지막 멜로디 리스트의 값에 #을 더해준다.
5. 처리가 완료 되었고 입력된 m 역시 #을 변환시켜준다.
6. 이후 sliding window를 이용하여 비교한다. --> 리스트이기 때문에 최적화된 검색 기법을 이용해야했음
7. 그러고 flag를 통해 동일한 내용이 있다면 비교를 위한 same_list 에 넣어준다.
8. 같은 곡이 여러개일때, 시간을 기준으로 그리고 시간이 같다면 먼저 들어 온 순서이기 때문에 sort 의 key를 노래 길이대로 정렬한다. 이때 들어 온 순서는 append를 통해 이미 순서대로 되었으므로 신경쓰지 않아도 된다.
9. 끝!
> 220919 박동준 프로그래머스 [3차] 방금그곡 풀이

- 220919/김광희_programmers_[3차] 방금그곡.java
( 문제 풀이 )
1. 먼저 네오가 기억한 멜로디를 담은 문자열에서 #이 붙은 문자를 "소문자"로 변환
2. 방송된 곡의 정보를 담고 있는 배열길이 만큼 반복을 한다
- 여기서, ',' 를 기준으로 배열 원소들을 나눠주고, ':'를 이용하여 시작 시간, 끝 시간을 구해 전체 노래 재생 시간을 구함
3. 음악의 길이보다 "재생된 시간이 길 경우" -> 음악은 끊김 없이 처음부터 반복 해서 재생하여 "음악 정보"를 저장한다.
4. 음악 길이보다 <재생된 시간이 짧을 때는> 음악 재생시간 만큼 "음악 정보"를 저장해 준다.
5. 음악 정보에  네오가 기억한 멜로디가 포함되어 있는지 여부와, 재생된 시간까지 비교함으로 써 answer을 구함
6. 만약 최대 재생 시간 변수가 갱신되었다면 answer을 반환, 그렇지 않다면(일치하는 음악이 없다면) "(None)"을 반환
> 220919 김광희 프로그래머스 [3차] 방금그곡 풀이

- 220919/안영원_programmers_[3차] 방금그곡.java
처음에 문제 이해를 못해서 시간이 좀 소모했다.
주어진 노래는 재생된 시간만큼 반복해서 재생이 되어서 ABC일 때 7분이라면 ABCABCA 라는 전체 멜로디가 된다.
그래서 해당 전체 멜로디안에 네오가 기억한 멜로디가 포함이 되어있다면 일치하는 것이고 일치 여부는 contains를 통해 쉽게 확인할 수 있다.
근데 멜로디가 한 단어뿐 아니라 A#과 같이 두개가 합쳐진 단어도 있기 때문에 해당단어를 하나의 단어로 바꿔주는 작업이 필요하다.
문제에서 사용하지않는 대문자 알파벳이나 소문자 알파벳으로 바꾸어주면 쉽게 해결이 가능하다. (이 부분은 도움을 좀 받음)
일단 너무 졸려서 완벽히 풀이해서 풀지 못해서 아쉽
> 220919 안영원 프로그래머스 [3차] 방금그곡 풀이

- 220921/강소현_programmers_양궁대회.java
- 우선순위 큐 썼읍니다.. `라이언이 가장 큰 점수 차이로 우승할 수 있는 방법이 여러 가지 일 경우, 가장 낮은 점수를 더 많이 맞힌 경우` 조건 때문에 우선순위 큐 사용하고 `Comparator` 사용했습니다.
- 11개의 점수가 존재하는 과녁에 1 ~ 10개까지 맞춘 조합을 구합니다. 이후 어피치랑 라이언 점수를 계산해준 뒤 라이언이 과녁에 맞춘 배열을 찾아갔습니다.
- 8, 18 테케 자꾸 틀렸는데 라이언 점수와 어피치 점수를 비교할 때 `else if (max == r - a)` 해당 조건이 없어서..틀렸었습니다.
- 힘들었다
> 220921 강소현 프로그래머스 양궁대회 풀이

- 220919/장예찬_programmers_[3차] 방금그곡.py
[풀이과정]
1. #으로 된 것들을 한 글자로 치환
2. 내부에 같은 것이 있으면 길이 판별 후 정답 갱신
3. 반환
머리가 아파서 그런가 치환 대신 이상한 방법 씀
> 220919 장예찬 프로그래머스 [3차] 방금그곡 풀이

- 220921/안영원_programmers_양궁대회.java
실패한거 올려둠
모든 경우의 수를 다 찾아서 계산해보려고했는데 코드 속에 뭔가 오류가 있나봅니다.
오류를 찾지 못하겠음.
그래서 아래와 같이 다시 풀어보려고함.
<생각한 풀이 방법>
그냥 라이언 배열을 하나씩 만들어보면서 해보려고함 오늘 말고
10점에 이길경우에 해당하는 개수 넣어주면서 남은 화살하고 체크해서
화살이 부족하면 그 다음 depth로 넘어가지 않게하는 방식으로 가지치기
마지막 0점에서 화살이 남아있으면 0점에 화살을 다 소비하고나서
점수 계산 후 체크해주는 방식
그래서 최종 depth - 1에서 재귀를 끝나게 할 것임.
> 220921 안영원 프로그래머스 양궁대회 풀이

- 220921/김광희_programmers_양궁대회.java
( 문제 풀이 )
1. 중복 조합을 활용하여 < 라이언이 쏜 과녁 점수 저장 >
2. 구한 점수를 활용하여 어피치 정보 처럼 < 라이언의 정보도 > 동일하게 해당 점수에 맞춘 개수형태로 만들어준다.
3. 라이언 정보와, 어피치 정보가 둘다 과녁점수를 < 0개 맞춘 원소는 무시. > 
4. 라이언이 이긴경우( 라이언이 과녁 점수를 맞춘 갯수가 더 많다면 ) k점 즉 해당 socre 가져감
반대로 어피치가 이긴 경우 어피치가 해당 score 가져감
5. 라이언의과 어피치가 같을경우 어피치가 해당 score 가져간다. -> 문제에 기재 되어 있음
6. 최댓값이 (라이언 - 어피치)를 한 점수보다 작다면  -> 즉, < 라이언의 최종 점수가 더 크다면. >
최댓값 갱신 및 라이언의 정보를 answer 배열에 복사시켜 준다.
7. 라이언이 무조건 지거나, 비길경우 [-1] 배열을 return 
그렇지 않으면 answer 배열을 return으로 해결.
> 220921 김광희 프로그래머스 양궁대회 풀이

- 220914/장예찬_programmers_코딩 테스트 공부.py
[풀이과정]
DP로 푼다.
1. 알고력과 코딩력을 각각 행과 열로 두고 각 원소 값은 해당 알고력과 코딩력에 도달하는데 걸리는 시간을 적는다.
2. 알고력+1일 때와 아닐 때를 비교해서 작은 값으로 바꾼다
3. 코딩력+1일 때와 아닐 때를 비교해서 작은 값으로 바꾼다
4. 문제를 풀 수 있다면 풀었을 때와 아닐 때를 비교해서 작은 값으로 바꾼다.
5. 모든 i행과 j열에 대하여 2~4를 반복한다.
처음엔 2와 3을 행과 열의 인덱스로 계산할 수 있다는 생각을 하고 있었음.
> 220922 장예찬 프로그래머스 코딩 테스트 공부 풀이

- 220921/박동준_programmers_양궁대회.py
1. 백트래킹
2. 조건을 잘 읽었어야함, 같은 점수차이일때 낮은점수를 더 많이 맞춘 과녁을 결과로 넣어줘야함
3. 점수가 같을 때 비교문을 넣어줌
4. 이외에는 조건에 맞게 실행하면댐
> 220921 박동준 프로그래머스 양궁대회 풀이

- 220922/박동준_programmers_후보키.py
1. 유일성을 만족시키는 열간의 조합을 찾는다.
2. 찾았다면, 조합 ex) 1,2 1,2,3을 통해 만들 수 있는 조합을 찾는다.
3. 이 조합이 만약 유일성을 만족시키는 리스트에 들어가있다면 최소성을 만족하지 못하기 때문에 제외
4. 들어있지 않다면 추가시켜준다.
이 문제의 핵심은
1. 리스트를 조합에 따라 열끼리 재가공 시킨 후 집합을 통해서 비교하는것
2. 이후 최소성을 만족하는지 탐색하기 위해 조합으로 최소성 검증
을 해야 문제가 풀린다.
> 220922 박동준 프로그래머스 후보키 풀이

- 220926/김광희_boj_1162_도로포장.java
( 문제풀이 )
1. graph에  양방향 그래프 정보를 입력 받아 셋팅해 준다.
2. 최단 거리테이블 distance를 2차원 배열로 선언 및 초기화 해준다. -> distance[정점][포장 횟수 ] 로 사용하기 위해서
즉, 해당 정점에 도로 포장을 하고 간 경우와, 포장을 하지 않고 간 거리를 저장하며 가기 위해서
3. 최종 정점 N까지 도로 포장을 하지 않은경우와 도로 포장을 한 경우 중 더 빠르게 도로를 통과하는 시간을 min 변수에 저장 및 출력한다.
문제에 대한 힌트를 보고 해결하였습니다 ... 어렵네요 ...
> 220926 김광희 백준 1162 도로포장 풀이

- 220928/안영원_boj_1445_일요일 아침의 데이터.java
음 생각보다 좀 쉽게 풀린듯
문제를 잘 읽어야하는 문제였다.
우선순위큐로 쓰레기를 적게 넘어온 순서대로 같다면 인접한 쓰레기가 적게 온 순서대로 정렬해서 탐색하였으며,
지나올 때 쓰레기를 지나왔다면 인접한 쓰레기가 있는 것은 신경쓰지않고 쓰레기를 지나온 횟수만 추가하고
빈 칸이라면 인접한 쓰레기가 있는지 확인하고 인접한 쓰레기 횟수를 증가시켜준다.
그리고 마지막 칸에 도착하는 것은 카운트하지 않기 때문에 쓰레기 횟수를 추가하면 안된다.
헷갈렸던 것은 쓰레기가 있는 칸에 도달했을 때 인접한 칸에 쓰레기가 있는 것은 신경쓰지 않는 부분이었다.
인접한 쓰레기를 체크할 때는 무조건 해당하는 칸이 빈칸이어야한다.
문제를 열심히 읽자 !!
> 220928 안영원 백준 1445 일요일 아침의 데이트 풀이

- 220928/박동준_boj_1445_일요일 아침의 데이트.py
근본 원리 : bfs
쓰레기 좌표 주변 미리 # 으로 변환 하고, 움직일 좌표가 # 이라면, 근처 값 증가
heapq를 이용하여 가장 값이  작은 배열부터 꺼냄 이때 작은 값의 기준은 쓰레기를 안밟고 지나가는것
따라서 (쓰레기 카운트, 근처 카운트, x,y)로 묶어서 보내줌
마지막 도착 지점에 도달했을때 최적인 경우가 결론에 나오므로 break
--
처음 풀이,
어떤 경우가 도착했을 때 최적인지 모르기 때문에 마지막 지점에 도달해도, 다른 경로가 모두 탐색될때까지 기다렸음.
근처인지 판별 및 쓰레기 좌표인지 구분하여 다음 구간에 넣어주는것은 동일했으나,
최적의 좌표부터 꺼내게 했으면 메모리초과가 안났음
deque를 이용한 풀이가 문제였고 heapq로 변경!
> 220928 박동준 백준 1445 일요일 아침의 데이트 풀이

- 220928/강소현_boj_1445_일요일 아침의 데이트.java
> 220928 강소현 백준 1445 일요일 아침의 데이트 풀이

- 220928/김광희_boj_1445_일요일 아침의 데이트.java
( 문제 풀이 )
1. 쓰레기 밟은 횟수가 가장 적은 것을 꺼내준다, 만약 동일하다면 쓰레기 옆을 지나가는 칸의 개수가 적은 것을 꺼내줌
2. 4방 탐색으로 이동할 칸에 쓰레기가 존재한다면 쓰레기 밟은 횟수를 증가해서 넣어준다.
존재 하지 않다면 해당 칸에 또 4방 탐색으로 이웃한 곳에 쓰레기가 있는지 검증을 해 주고 쓰레기 옆을 지나간다면 
< 쓰레기 옆을 지나가는 칸의 개수를 증가 >시켜 주고 맨 밖의 쓰레기가 존재하는지의 4방 탐색 for문으로 바로 이동시켜준다.
3. 쓰레기도 밟지 않고, 쓰레기 옆을 지나가지도 않았다면 개수 증가 없이 "우선 순위 큐에 " 넣어줌
4. 꽃이 있는 위치에 도착했다면 현재까지 쓰레기 밟은 횟수, 쓰레기 옆을 지나가는 칸의 개수를  
min_garbage_count, min_next_count 변수에 넣어주고, while문 탐색 종료후 해당 변수를 출력해 준다.
> 220928 김광희 백준 1445 일요일 아침의 데이트 풀이

- 2209026/장예찬_boj_1162_도로포장.py
- 220921/220927_programmers_양궁대회.py
[풀이과정]
1. dfs로 풀이
2. 조건을 제대로 하지 못해 시간 내 실패
3. 솔루션 코드 참고로 풀이 완료
늦었지만 먼저 올립니다..
> 220921 장예찬 프로그래머스 양궁대회 풀이 

- 220929/안영원_programmers_전력망을 둘로 나누기.java
생각보다 간단하게 풀려서 코드 퀄리티도 조금 신경썼다.
송전탑과 연결된 전선들을 양방향 인접리스트를 통해 구현해주고
선을 하나씩 자르면서 생긴 이어진 송전탑의 개수를 비교하고 그 차이가 가장 작은 값을 리턴해준다.
> 220929 안영원 프로그래머스 전력망을 둘로 나누기 풀이

- 221005/강소현_boj_14891_톱니바퀴.java
- 테케 틀린 이유 ? 시계방향, 반시계방향 체크하는 부분에서 잘못됐었다..ㅎㅎ!
- 회전하기 전에 2, 6 부분에 맞닿는 극을 확인했다. `톱니바퀴 A를 회전할 때, 그 옆에 있는 톱니바퀴 B와 서로 맞닿은 톱니의 극이 다르다면, B는 A가 회전한 방향과 반대방향으로 회전`
- 극을 확인하고 체크할 수 있는 톱니바퀴는 회전해주었다.
> 221005 강소현 백준 14891 톱니바퀴 풀이

- 221005/안영원_boj_14891_톱니바퀴.java
각 톱니바퀴는 ArrayList를 통해서 표현하였다.
그래서 ArrayList 배열을 1~4로 만들어서 gearList[1] 이 1번 톱니바퀴를 의미하게되었다.
각 톱니바퀴 ArrayList는 총 8의 Size를 가지며 0번 index가 12시방향이고 7번 인덱스가 11시 방향이 된다.
이 문제는 회전 여부를 모두 확인한다음 동시에 회전이 이루어진다.
그래서 rotate 배열을 통해 회전여부를 기록해두고 한꺼번에 회전을 해주었다.
회전 확인은 총 3번 양쪽으로 확인하는데 이유는 1번 톱니바퀴를 회전시키면 4번까지 확인하려면 3회 필요하기 때문이다.
왼쪽과 오른쪽을 각각 확인하며 자석의 극이 같아서 회전을 더 이상하지않는다면 boolean 통해 해당 방향으로는 더 이상 확인안하게끔 한다.
회전이 가능하다면(N극과 S극이라면) 현재 위치와 반대방향으로 rotate에 표시해준다.
회전여부를 모두 판단했다면 기록에 맞게 회전해준다.
톱니바퀴가 시계방향으로 회전한다면 제일 뒤쪽에 있는 숫자를 뺴서 제일 앞에 넣어주고
반시계방향이라면 제일 앞에 있는 숫자를 빼서 제일 뒤에 넣어주었다.
모든 과정이 완료되었다면
12시 방향인 0 index에 있는 숫자를 통해 합을 계산했다.
합은 1, 2, 4, 8이므로 2의 거듭제곱이기 때문에 Math.pow로 계산해주었다.
> 221005 안영원 백준 14891 톱니바퀴 풀이

- 221006/안영원_programmers_k진수에서 소수 개수 구하기.java
- 221006/안영원_programmers_파괴되지 않은 건물.java
**파괴되지 않은 건물**
전체를 통째로 시뮬레이션을 돌리면 시간초과가 날 수 밖에 없다.
예전에 풀이를 참고해서 풀었었는데 누적합을 이용한다.
주어진 r1 c1 r2 c2 위치에 degree를 표시하고
해당 위치의 반대편 꼭짓점에 -degree를 표시해서 전체적인 구간을 표시해둔다
즉 5 0 0 -5
0  0 0  0
-5 0 0 5
이렇게 좌측과 우측하단에 degree와 반대편에 -degree를 표시하고
전체를 체크하고 나면 상하, 좌우로 이전 값과 더한 값을 기록하고 전체 값을 원래 배열에 더해주면 해결 된다.
**k진수에서 소수 개수 구하기**
k진수로 n을 변환을 한 다음에 소수인지 확인하는 코드를 통해 확인한다.
소수를 확인하는 코드는 2부터 제곱근까지 나눠지는지 여부를 체크해서 확인하였다.
> 221006 안영원 프로그래머스 파괴되지 않은 건물 풀이

- 221005/장예찬_boj_14891_톱니바퀴.py
- 221012/장예찬_programmers_구멍보트.py
[풀이과정]
1. 사람 몸무게를 정렬한다.
2. 아직 안 탄 사람 중 가장 가벼운 사람과 가장 무거운 사람이 같이 탈 수 있다면 필요한 구명보트는 사람보다 하나 줄어든다.
3. 이는 항상 최적 값을 나타낸다
> 221012 장예찬 프로그래머스 구명보트 풀이

- 221012/안영원_programmers_구명보트.java
2명의 짝을 최대한 지어주어야하기 때문에
간단히 생각해도 가장 몸무게가 적게 나가는 사람과 많이 나가는 사람을 묶어주어야한다.
그래서 정렬을 해주었고
가장 몸무게가 적게 나가는 사람과 같이 탈 수 있는 사람을 순서대로 찾아본다.
만약 둘이 탈 수 없다면 가장 많이 나가는 사람은 혼자 탈 수 밖에 없기 때문에 해당 부분에 대한 처리를 하면서 진행한다.
> 221012 안영원 프로그래머스 구명보트 풀이

- 221012/김광희_programmers_구명보트.java
( 문제풀이 )
1. 사람들의 몸무게를 담은 배열 people을 오름차순으로 정렬
2. 가장 가벼운 사람과 가장 무거운 사람의 합이 무게제한"limit" 보다 작거나 같다면
가장 가벼운 사람의 인덱스 위치 증가, 가장 무거운 사람의 인덱스 위치 당겨줌. 그리고 구명 보트의 개수 증가.
3. 2명이서 보트를 탈 수 없는 경우는 구명 보트의 개수만 증가 -> 혼자 보트를 타야하는 경우
( 문제 상세 과정 풀이 )
50 50 70 80
1단계 50 80 -> 무게 제한 100보다 합이 크다 -> 구명 보트 개수만 증가 --> answer : 1
2단계 50 70 -> 위와 마찬가지임 -> 구명 보트 개수만 증가 --> answer : 2
3단계 50 50 -> 무게제한보다 작거나 같기 때문에 < 최소 인덱스 증가 > 및 < 최대 인덱스 감소 > 및 구명 보트의 개수 증가 --> answer : 3
여기서 max_index = 0, min_index = 1 이기 때문에 for문 조건 max_index >= min_index 에 걸리지 않기 때문에 for문에서 나옴
최소 인덱스가, 최대 인덱스 보다 크기 때문에 조건에서 true가 아닌 false 상태이기 때문
> 221012 김광희 프로그래머스 구명보트 풀이

- 221013/김광희_boj_2285_우체국.java
( 문제 풀이 )
1. 마을 위치 순으로 오름차순으로 정렬한 뒤, 1번째 마을부터 탐색하며 각 마을에 위치한 사람의 수를 sum 변수에 누적
2. 탐색 중에 더해진 사람의 수가 마을 전체 총 인구수의 절반보다 크거나 같을경우 < 해당 마을 위치를 return >
> 221013 김광희 백준 2285 우체국 풀이

- 221013/강소현_boj_2285_우체국.java
저는 그리디인 거 알고 풀었습니다. 제가 요즘 그리디만 풀거든요 ! 푸항항 😜
1. 마을 위치를 오름차순으로 정렬합니다.
2. 마을 사람들의 합을 구하고 중간값을 구합니다. `(mid + 1) / 2`
3. 각 마을을 방문할 때마다 사람들의 합을 구하고 mid 값보다 크거나 같을 때 해당 마을 좌표를 반환합니다.
> 221013 강소현 백준 2285 우체국 풀이

- 221013/장예찬_boj_2285_우체국.py
<풀이과정>
1. 좌측 머릿수와 우측 머릿수의 개수의 차가 최소인 위치를 찾는다.
<주의>
- 처음엔 모든 입력이 정렬되어 있는 줄 알았는데 아니었음.
- 좌측이랑 우측 머릿수 차이를 전체 머릿수와 좌측 머리 수 만으로 수학적으로 구하려고 했는데 그냥 간단하게 생각하는 편이 훨씬 빨리 풀이할 수 있음.
> 221013 장예찬 백준 2285 우체국 풀이

- 221017/강소현_boj_6593_상범 빌딩.java
전형적인 BFS 문제 + 3차원 BFS 문제구나 정도 였습니다. 3차원 배열이다보니 문제 조건대로 동서남북상하 탐색 가능하게 했습니다. 그리고 요즘 String.format()을 열심히 써보고 있습니다.(?
> 221017 강소현 백준 6593 상범 빌딩 풀이

- 221017/안영원_boj_6593_상범 빌딩.java
기존 2차원 배열의 탐색에서 3차원 배열 탐색으로 상하가 추가로 생긴 것 이외에는 특별할 것이 없었다.
동서남북 탐색에 위층과 아래층을 탐색할 상하를 추가해주고 기존 BFS와 동일하게 진행하였다.
> 221017 안영원 백준 6593 상범 빌딩 풀이

- 221017/김광희_boj_6593_상범 빌딩.java
( 문제 풀이 )
1. 처음 시작 층에서 'S'인 시작 좌표를 (sx, sy, sz) 에 저장한다.
2. sx, sy, sz 좌표를 기준으로 bfs 탐색을 해준다.
- 여기서 'E(도착지점)'에 도착하면 bfs 탐색을 종료하고 이동한 최단거리를 출력 양식에 맞게 출력해 준다. 
-> "Escaped in (시간) minute(s)."
- 모든 탐색을 다 했지만 'E(도착지점)'에 도착하지 못한다면 "Trapped!" 출력 (줄 바꿈 해줘야 함!)
> 221017 김광희 백준 6593 상범 빌딩 풀이

- 221017/장예찬_boj_6593_상범 빌딩.py
<풀이과정>
1. BFS로 풀이한다.
2. 3차원이므로 queue가 너무 커져 메모리가 터질 수 있다. queue에 삽입 전에 방문을 미리 체크한다.
3. 방문체크는 방문한 곳을 #(벽)으로 만들면 된다.
> 221017 장예찬 백준 6593 상범 빌딩 풀이

- 221019/안영원_programmers_행렬 테두리 회전하기.java
회전해야할 테두리를 받아서 상하좌우 테두리를 각각 회전시켜준다.
회전하면서 각 칸의 숫자 중 제일 작은 숫자를 리턴해서 배열에 넣어 반환해주면 끗
> 221019 안영원 프로그래머스 행렬 테두리 회전하기 풀이

- 221019/강소현_programmers_행렬 테두리 회전하기.java
<풀이>
회전해야 할 배열 `map` 생성 후 회전해야 할 테두리를 회전 시켰습니다. 회전 시키는 과정에서 최솟값 갱신도 했습니다.
(좀 더 효율적으로 푸시는 법 아시는 분... 구합니다.)
> 221019 강소현 프로그래머스 행렬 테두리 회전하기 풀이

- 221019/장예찬_programmers_행렬 테두리.py
<풀이과정>
1. 행렬 초기화
2. 오른쪽, 아래, 왼쪽, 위 이동 리스트 초기화
3. 해당 방향마다 x, y축이 한 칸 더 벗어나면 방향 전환
4. 완료되면 최소 값을 정답 리스트에 추가
> 221019 장예찬 프로그래머스 행렬 테두리 회전하기 풀이

- 221019/김광희_programmers_행렬 테두리 회전하기.java
( 문제 풀이 )
1. row * columns 크기 만큼 1부터 row *columns 까지의 숫자를 한줄씩 map에 채워준다.
2. 직사각형 모양의 범위에서 시작 지점 부터 끝지점 까지 map 안에 있는 숫자를 시계방향으로 회전 시켜준다. 
-> 여기서 회전하면서 계속 최솟값을 갱신해 준다. -> 이 중 가장 작은 값을 answer 배열에 순서대로 담아준다.
생각의 흐름대로 풀다보니 어디서 조금 막혀서 .. 델타배열 사용해서 해 보았습니다. 추후 회전 부분은 함수로 떼어내면 더 효율적 일듯 합니다.
> 221019 김광희 프로그래머스 행렬 테두리 회전하기 풀이

- 221020/안영원_boj_20057_마법사 상어와 토네이도.java
까다로운 구현 문제
기본적인 토네이도의 움직임은 달팽이 문제로써
같은 거리로 두 방향으로 이동 후 이동 거리 증가 후 다음 두 방향으로 이동하는 것을 반복
모래 흩뿌리기는 모래가 흩뿌려지는 것에 대해 번호를 지정해놓고 상하좌우 움직이듯 각 흩날리는 위치를 sandR과 sandC로 지정
2차원 배열로 [움직이는 방향][모래 번호] 로 사용
그 외엔 문제에서 주어진 대로 구현
> 221020 안영원 백준 20057 마법사 상어와 토네이도 풀이

- 221024/강소현_programmers_콜라 문제.java
<문제 풀이>
- `n (상빈이가 가지고 있는 빈 병 개수) / (a) 마트에 주어야 하는 병 수) * b(a개의 빈 병을 가져가면 교환해주는 콜라 병 수` → 상빈이가 받을 수 있는 콜라 병 개수
- n % a → 당장 교환할 수 없는 병 : 빈 병 개수에 포함시켜 다시 탐색
- 그냥 단순 구현문제였다.
> 221024 강소현 프로그래머스 콜라 문제 풀이

- 221024/안영원_programmers_콜라 문제.java
문제에서 주어진 대로 식을 구현하면된다.
처음엔 나머지를 따로 분리해서 식을 세웠다가 안되길래 통합했더니 됬다.
생각보다 간단했던 수학 문제.
> 221024 안영원 프로그래머스 콜라 문제 풀이

- 221024/김광희_programmers_콜라 문제.java
( 문제 풀이 ) 
1. n / a 가 0이면 while문 탈출 ->  상빈이가 받을 수 있는 총 콜라 수 
- while 문 안에서  받는 콜라 수(receving_coke)와, 상빈이가 마트에 빈병을 가져가고 남은 콜라(remaider_coke)를  저장 
- answer에 받는 콜라 수(receving_coke) 누적
- n을 받는 콜라 수와, 마트에 빈병을 가져가고 남은 콜라 수 -> 즉 상빈이가 현재 들고있는 콜라 수로 초기화 시켜준다.
단순 주어진 문제대로 구현하면 되는 문제다.
> 221024 김광희 프로그래머스 콜라 문제 풀이

- 221024/박동준_programmers_콜라 문제.py
주어진 내용대로 수학식을 만든다, 이때 교환할 수 있는 갯수보다 가진 유리병의 갯수가 작아지면 반복문을 중단한다.
> 221024 박동준 프로그래머스 콜라 문제 풀이 

- 221024/장예찬_programmers_콜라 문제.py
- 221026/장예찬_boj_12764_싸지방에 간 준하.py
<풀이과정>
O(n)일 경우 재귀를 이용하면 파이썬에선 반드시 재귀 제한이 발생할 수 밖에 없어 런타임 에러가 발생한다. 참 어이 없는 언어가 아닐 수 없다. 제한을 해제하고 푼다.
1. n을 a로 나눈 몫을 k라고 한다.
2. b의 k 곱을 l이라고 한다
3. k가 0보다 클 때 l+solution(a, b, n - a*k + l)을 재귀한다.
4. k가 0보다 작으면 0을 반환한다.
> 221024 장예찬 프로그래머스 콜라 문제 풀이

- 221027/안영원_boj_1715_카드 정렬하기.java
주어진 카드를 비교할 때 가장 효율적이게 비교를 하는 방법을 찾기
예시에서는 10 20 40이 주어졌다.
해당 숫자를 작은 순서대로 합쳐서 계산해주면 가장 효율적이게 된다.
그래서 우선순위큐에 해당하는 숫자들, 비교한 합을 집어 넣어주면서 계산하였다.
큐의 크기가 1이 된다면 탈출 후 합한 값을 출력했다.
> 221027 안영원 백준 1715 카드 정렬하기 풀이

- 221026/김광희_boj_12764_싸지방에 간 준하.java
( 문제 풀이 )
1. 각 사람의 시작 시간과, 종료시간을 Person 객체 배열에 저장한다. 
-> Person 객체에 담겨져 있는 정보 중 시작 시간을 기준으로 오름차순 정렬, 
시작 시간이 같다면 종료시간 오름차순 정렬을 한다.
2. 해당 자리에 앉은 사람의 횟수를 구하기 위해 계수 용도의 배열(arr)을 선언 및 초기화 한다.
3. 현재 번호에 앉아 있는 인덱스 표시를 위한 (empty_idx)변수를 활용한다.
4. 사람의 수 만큼 반복문을 돌리는대 
(1)- 먼저 컴퓨터를 이용하고 있는 사람의 끝나는 시각과, 해당 자리 번호를 담는 우선순위 큐가 비어있지 않고,
"현재 사람의 시작 시간" 보다, 제일 먼저 싸지방에 < 먼저 와서 앉은 사람의 종료 시간이 더 짧거나 같은 경우 > 
-> 해당 사람의 컴퓨터 번호에 앉는다.
(2)- < 번호가 작은 자리에 앉아 있던 사람 중 > 자리가 비어 있는 곳이 있다면
해당 번호에 새로운 사람이 앉는다
(3)- 비어있는 곳이 없다면 가장 작은 번호에 앉아 있는 사람 < 다음 인덱스에 > 새로 사지방에 들어온 사람이 앉는다.
5. 컴퓨터의 최소 개수 X를 출력 하고 줄 바꾼 뒤, 1번 자리 부터 X번 자리까지 순서대로 각 자리를 사용한 사람의 수를 띄어쓰기 간격으로 출력
> 221026 김광희 백준 12764 싸지방에 간 준하 풀이

- 221031/박동준_programmers_스킬트리.py
문제에 예시가 바로 나와있다.
카드 배열에서 작은 숫자끼리 더해준다.
처음에는 정렬 후 작은값을 arr 에 추가시켜주고
반복시켰으나 여기서 한가지 오류가 발생한다.
중간에 합친 값이 기존 배열에있는 값보다 작은값이라면 이걸 먼저 더해줘야한다.
그래서 반복문을 순회할때마다 정렬을 시켰으나 `시간초과`
그래서 heapq를 이용하여 최적화 시켰다.
> 221027 박동준  백준 1715 카드 정렬하기 풀이

- 221027/장예찬_boj_1715_카드 정렬하기.py
<풀이과정>
1. heapq 를 이용해서 정렬된 힙을 만듬
2. 첫번째 두번째 인덱스를 pop해서 합치고 answer에 더함
3. 힙에 더한 값 삽입
4. 힙의 길이가 1이 될 때까지 반복
> 221027 장예찬 백준 1715 카드 정렬하기 풀이

- 221031/장예찬_programmers_스킬트리.py
<풀이과정>
1. skill을 체크할 때마다 큐로 만든다.
2. 큐 내부에 존재하면 큐에서 스킬을 빼면서 스킬트리를 순회하며 큐에서 나온 원소와 일치하는지 체크한다.
3. 다 통과시 answer += 1
4. answer 출력
> 221031 장예찬 프로그래머스 스킬트리 풀이

- 221031/박동준_programmers_스킬트리.py
1. 스킬과 관련된 문자열만 추출한다.
2. 해당 문자열의 길이만큼 skill을 잘랐을때 동일해야만 올바른 스킬트리이다 다르면 순서자체가 잘못된거
3. 끝
> 221031 박동준 프로그래머스 스킬트리 풀이

- 221031/강소현_programmers_스킬트리.java
<문제 풀이>
skill_trees에 skill에 포함된 원소가 아닌 것을 다 제거하고 substring으로 문자열 비교해서 카운트했습니다.
> 221031 강소현 프로그래머스 스킬트리 풀이

- 221031/김광희_programmers_스킬트리.java
( 문제풀이 )
1. 유저들이 만든 스킬트리(skill_trees)에 있는 원소의 문자열 길이 만큼 반복문을 돌리면서 
선행 스킬 순서(skill)에 존재하는 문자일때 StringBuilder에 추가해준다.
2. skill의 부분 문자열(맨 뒤 부분을 줄여줌)을 확인하면서 만든 StringBuilder와 같은지 확인.
만약 같지 않으면 부분 문자열 맨 뒤 부분을 줄여주기 위해 size를 1 감소 시킴 
-> 선행 스킬 순서가 항상 먼저 배워야하기 때문에 "맨 뒤 부분부터 줄여주는 생각을 가짐".
< 여기서 주의할 점 ! >
- 유저들이 만든 스킬 트리가 선행 스킬 트리와 아무것도 같지 않은 경우는 -> "위 순서에 없는 다른 스킬(힐링 등)은 순서에 상관없이 배울 수 있습니다." 에 해당하기 때문에 사용 가능한 스킬 트리라는 의미이다.
-  따라서 size 가 -1 보다 클 경우를 while문 탈출 조건을 둠으로써 아얘 비어있는 값 까지 비교하게 만들어 주었다.
> 221031 김광희 프로그래머스 스킬트리 풀이

- 221107/강소현_programmers_야간 전술보행.java
<풀이>
- scope의 경우 정렬이 되어 있지 않는 경우가 있으므로 정렬
- 경비병의 근무시간과 겹치지 않게 `근무시간 + 휴식시간`의 나머지 연산을 활용해 확인. 나머지 값이 근무 시간보다 크거나 같으면 안 됨. (이는 경비병의 근무 시간을 겹치게 됨)
> 221107 강소현 프로그래머스 야간 전술보행 풀이

- 221107/장예찬_programmers_야간 전술보행.py
<풀이과정>
1. 정찰 구간들을 순회
2. 구간의 앞 뒤를 정렬함
3. 화랑이 이속은 1이니깐 거리 1을 시간 1로 침
4. 화랑이 정찰구간에 도착할 때까지 경비가 (감시+휴식)을 몇 번 반복했는지 나머지로 계산
5. 나머지가 만약 경비의 감시 시간과 겹치면 걸린 것이다
6. 최소 값 갱신
> 221107 장예찬 프로그래머스 야간 전술보행 풀이

- 221109/강소현_programmers_푸드 파이트 대회.java
<풀이>
- food[0]은 물이므로 food[1]부터 체크
- food[i] / 2 만큼 i를 Stringbuilder에 담아주면 됨
- 반복 문자열의 경우 for문 대신 repeat를 사용해서 풀 수 있음
> 221109 강소현 프로그래머스 푸드 파이트 대회 풀이

- 2022_09_Study/220928/장예찬_boj_1445_일요일 아침의 데이트.py
- 2022_09_Study/220929/장예찬_programmers_전력망을 둘로 나누기.py
- 221109/장예찬_programmers_푸드 파이트 대회.py
<풀이과정>
1. BFS 로 풀이
2. 인접 쓰레기를 문자열로 재배치
3. heapq를 이용해서 쓰레기 밟은 수와 인접 쓰레기 밟은 수를 계산해서 BFS 진행
<풀이과정>
1. BFS로 풀이한다.
2. tree를 절단하고 각 부분을 bfs로 돌려서 이어진 수를 센다.
3. 센 것의 차이의 절대 값을 최소로 만든다.
4. 최소 값을 반환
<풀이과정>
1. map을 이용한 람다식으로 반복하는 문자열 만들기
2. 문자열 조합 (1.의 문자열 + 0 + 반대로 뒤집은 1.의 문자열)
3. 반환
> 220928 장예찬 백준 1445 일요일 아침의 데이트 풀이 & 220929 장예찬 프로그래머스 전력망을 둘로 나누기 풀이 & 221109 장예찬 프로그래머스 푸드 파이트 대회 풀이

- 221109/박동준_programmers_푸드 파이트 대회.js
1. 1일 경우 양 선수가 먹지 못하기때문에 범위를 1 보다 클 경우로 제한
2. 1보다 클때, 2로 나눈 몫을 구함
3. 몫만큼 수를 반복시킴 (idx)
4. 이후 0번 인덱스의 물은 1개만 있고 중앙에 0을 더해줌 뒤에 값은 앞에 구한 string을 뒤집어준다.
5. 끝!
> 221109 박동준 프로그래머스 푸드 파이트 대회 풀이

- 221109/안영원_programmers_푸드 파이트 대회.java
배열 순서대로 칼로리가 기록되어 있어서 앞쪽부터 탐색하면서 기록한다.
배열의 0번은 물을 나타내므로 1번부터 탐색하면서 푸드 파이트에 참여하는 두 명이 먹어야하므로 2로 나눠서 가능한 만큼 결과에 추가하여준다.
음식의 배치는 가운데 물을 기준으로 짝을 이루고 있기때문에 음식을 처음 배치할 때 StringBuilder에 담아두고
1. answer에 해당 배치를 더해주고
2. 물인 0을 더해주고
3. StringBuilder의 reverse를 이용해서 남은 배치를 더해주고
출력하였다.
> 221109 안영원 프로그래머스 푸드 파이트 대회 풀이

- 221109/김광희_programmers_푸드 파이트 대회.java
( 문제 설명 )
food[0] = 물
그 뒤 i번 음식의 수이다.
1번 테케로 예시
1번 : 3개 , 2번 : 4개 , 3번 : 6개 -> 1번 음식 1개는 대회에 사용하지 못함
즉, 음식의 개수가 짝수개가 있어야 서로 먹을 수 있다. 
( 문제 풀이 )
1. 해당 하는 "i번 음식의 수를" 2로 나눈 몫 만큼 StringBuilder에 붙인 뒤, 
"0" 을 더하고, StringBuilder에 붙인 수를 거꾸로 더 해주면 해결!
> 221109 김광희 프로그래머스 푸드 파이트 대회 풀이

- 221110/안영원_boj_1449_수리공 항승.java
물이 새는 곳을 앞부분부터 확인하기 위해서 일단 정렬을 해준다.
테이프는 물이 새는 곳이 A일 때 `"A - 0.5 ~ A + 0.5"` 부분까지 붙여야 물이 새지않는다.
정렬이 되어 번호가 낮은 지점부터 테이프 길이만큼 붙이고 다음 지점까지 테이프가 붙여져 있다면 넘어가고 아니면 테이프를 겹쳐 붙이는 식으로 진행한다.
그래서 첫 번째 구멍 A를 기준으로 먼저 테이프 길이만큼 붙이면 `"A + L(테이프길이) - 0.5"`가 현재 붙인 테이프의 끝점이 되고
다음 지점이 B일 때 `B + 0.5` 부분보다 테이프 끝점이 짧다면 새로 테이프를 붙이고 다시 끝점을 바꾼다.
아니라면 그 다음 지점을 탐색한다.
이를 쭈욱 반복
코드에 주석 적음 ..!
> 221110 안영원 백준 1449 수리공 항승 풀이

- 221110/박동준_boj_1449_수리공 항승.py
1. 0.5센치라는 위치를 특정하기 위해 그냥 커다란 10000 길이의 빈 리스트 만듬
2. 구멍의 위치는 구멍 번호 곱하기 2 마이너스 1 하면 새로 만든 배열 인덱스와 동일
3. 해당 구멍 기준으로 인덱스 번호 -1 +1번까지 스티커가 있는지 확인
4. 있으면 넘어가기
5. 없으면 채워진 스티커 갯수만큼 스티커 붙이는 위치를 미루고, 그 범위만큼 체크
> 221110 박동준 백준 1449 수리공 항승 풀이

- 221117/안영_programmers_[3차] n진수 게임.java
문제 이해를 잘못해서 시간이 좀 걸렸습니다.
t가 외쳐야할 숫자의 개수라서 t * m만큼 n진수로 변환해두고
외쳐야할 부분만 잘라서 출력하면됩니다.
진수 변환이랑 출력은 라이브러리 검색해서 사용했습니다. 좋은거 배웠네여..
처음엔 전체 사람이 t만큼 외치는 줄 알았어요. 휴우우우우우.....
코드 3번 엎었다.
> 221117 안영원 프로그래머스 [3차] n진수 게임 풀이

- 221117/박동준_programmers_[3차] n진수 게임.py
1. 진수를 구하는 함수 division을 만든다,
2. 모든 진수를 만드는 방법인 진수에 따라 값을 계속 나누어 몫이 0이 될때까지 변경시켜준다.
3. 이후 미리구할 갯수인 t와 사람수 m 만큼 곱하면 총 구해야하는 수의 범위가 나온다.
4. 이대로 함수 계속 돌려서 값을 구한다.
5. 이후 p-1번째 부터 사람수인 m 만큼 간격으로 값을 구하면 끝!
> 221117 박동준 프로그래머스 [3차] n진수 게임 풀이

- 221117/장예찬_programmers_[3차] n진수 게임.py
<풀이과정>
- 자세한 내용은 코드 주석 참조
1. n진법을 표현하는 함수 작성
2. 0부터 t * m까지 n진법으로 변환한 수 저장
3. p번째 사람이 말해야 하는 단어들만 리스트에 추가
4. 리스트를 문자열로 join하여 반환
> 221117 장예찬 프로그래머스 [3차] n진수 게임 풀이

- 221121/박동준_programmers_과일 장수.py
1. 길이만큼 최대값을 도출해야함, 큰수부터 내림차순 정렬
2. 이후 for문의 간격을 m -> 한 박스에 들어가는 사과 갯수 만큼 간격을 준다
3. i,i+m-1 구간까지의 배열을 slice 하고, 가장 작은값을 구해준다
4. 이후 m*min_num을 answer 에 더해준다.
5. 만약 이때, 슬라이싱 한 배열의 길이가 m 보다 작다면 다 담지 못하기때문에 멈춘다.
> 221121 박동준 프로그래머스 과일 장수 풀이

- 221121/강소현_programmers_과일 장수.java
와 내가 젤 더럽게 풀었을 거 같은데 나중에 코드 수정 좀 할게요^^.....와~~~~! 오늘은 좀 쉴래 ~!
> 221121 강소현 프로그래머스 과일 장수 풀이

- 221121/김광희_programmers_과일 장수.java
( 문제 풀이 )
1. 배열을 list에 담아, 가장 큰 사과 점수 순으로 즉, 내림차순으로 정렬해 준다.
2. list 사이즈 보다 크거나 같거나, list 사이즈보다 (현재 인덱스 + 한 상자에 담는 사과의 개수 )가 크다면 while문 탈출
-> 배열 인덱스 범위를 넘는 것은 범위 문제, 
-> 한 상자에 들어가는 사과의 수 보다 작을경우 볼 필요가 없음. 가득 채워서 판매해야 최대 이익을 계산할 수 있기 때문
> 221121 김광희 프로그래머스 과일 장수 풀이

- 221121/장예찬_programmers_과일 장수.py
<풀이과정>
1. 정렬해서 푼다.
2. 정렬 후에 idx로 리스트 내포 조건문을 통해 m으로 나눈 나머지가 0인 것만 m과 곱 연산 하여 합산함.
> 221121 장예찬 프로그래머스 과일 장수 풀이

- 221123/박동준_boj_9466_텀 프로젝트.py
우선 한 사람이 그사람 지목하였을 때, 싸이클이 생성이 된다면 팀이 생김
테케에는 없는 예외케이스가 있는데 이 예외는
단순 싸이클이 아닌, 1->2, 2->3 ,3->4, 4->2 와같은 경우를 예시로 들 수 있음.
이 예외를 생각하지 않고, 처음에는 while을 통해 안되는 경우의 갯수를 점진적으로 제거했음
위의 예외 케이스가 떠올랐고, 하나의 지점에서 끝점이 어디까지인지 탐색하는 bfs 방식으로 접근하기로 하였음.
for문을 통해 방문하지 않은 지점이라면 while문을 시작함,
1. 시작 전 현재 나의 위치를 check라는 리스트에 추가,
2. while문을 통해 check의 마지막 값을 불러오고, 다음으로 갈 수 있는 값을 찾아옴
3. 이때 내가 나를 선택한 경우도 함께 처리 해 주기 위해서 현재 나의 위치를 방문처리함
4. 만약 다음으로 가는 지점이 방문 했던 곳이라면 2가지의 경우로 나뉨
- 1. 이미 방문 했던 장소를 한번 더 방문하는 싸이클이 생기는 경우
- 2. 그전 싸이클 검증을 통해 싸이클이 완성되지 못하고 끊기는 경우
5. 이때, 싸이클이 생성되었는지 확인하기 위해 다음으로 가는 지점의 번호가 check 리스트에 있는지 확인
6. 다음 가는 지점이 방문하지 않았다면, check에 다음으로 가는 위치 추가
결론, 한 지점에서 갈 수 있는 지점까지 방문하게 함
방문을 하는 과정에서 이미 방문 한 장소가 여태 지나온 과정에 있던 장소면 싸이클, 아니면 그냥 끝!
> 221123 박동준 백준 9466 텀 프로젝트 풀이

- 221124/강소현_boj_14503_로봇 청소기.java
<풀이>
- 청소한 부분은 `robot[r][c] = 2`로 마킹
```java
int[] dr = {-1, 0, 1, 0};
int[] dc = {0, 1, 0, -1};
// 3 0 1 2
```
- 왼쪽으로 회전 시 기준으로 로봇 청소기 탐색
- 벽을 만나거나 범위를 초과하면 d를 기준으로 회전 → 회전 후에 범위 체크 + 벽 유무 판단
- 재귀
> 221124 강소현 백준 14503 로봇 청소기 풀이

- 221123/장예찬_boj_9466_텀 프로젝트.py
<풀이과정>
1. dfs로 푼다.
2. 현재 탐색하는 dfs에서 순환 리스트 구조가 발생했는지 판별할 visitedSet과 이때까지 탐색해서 더 이상 탐색이 불필요한 visited 리스트, 그루핑이 완료된 finished 리스트로 나누어 dfs를 돈다.
3. 순환 리스트 구조가 발생하면 해당 순환의 finished를 True로 만들고 카운트를 올린다.
4. dfs의 반환 값을 계속 누적한다.
5. 인원 - 누적카운트가 답이다.
> 221123 장예찬 백준 9466 텀 프로젝트 풀이

- 221123/안영원_boj_9466_텀 프로젝트.java
<실패한 것>
BFS로 풀려고함.
팀을 인접리스트로 구성하고 시작점으로 다시 돌아올 수 있는지 확인하고 돌아온다면 팀이 있는 것
돌아오지 못하면 팀이 구성안된 것으로 판단.
혼자 팀을 하는 사람은 solo 배열에 true로 확인
팀이 구성된 멤버들도 solo 배열에 추가해서 한 번 더 체크되지않도록함
```
하지만 시간초과
DFS로 풀어야할 것 같음. 다음 기회에 계속..
```
---
<푼 것>
계속 틀려서 일단 풀이봤음
이미 팀이 생성된 인원이면
다시 체크하지 않게해야하고
팀을 체크했는데 구성되지 못한 인원도 다음 사람이 그 인원에 진입하면 똑같이 팀을 구성하지 못하기 때문에
해당 경우도 걸러주는 처리가 필요함 -> dontGo 배열
코드가 어캐 돌아가는지는 알겠는데 담에 이 문제를 보더라도 풀 수 있을 것 같지는 않음
> 221123 안영원 백준 9466 텀 프로젝트 풀이

- 221124/박동준_boj_14503_로봇 청소기.py
1. 방향벡터를 잡는다.
2. 현재기준 북쪽이라면 서쪽을 볼 수 있게 방향 수정을 해 준다
3. 그리고 해당 위치로 이동했을 때의 좌표가 벽이 아니면 이동
4. 벽이거나 이미 방문한곳이면, 방향을 회전했던 방향 기준 회전
5. 이때 모든 방향을 보게 되면, 다시 처음 방향으로 방향이 돌아옴
6. 후진이기 때문에 처음 방향의 이동해야하는 값을 반대로 빼줌
7. 조건대로 구현
> 221124 박동준 백준 14503 로봇 청소기 풀이

- 221124/안영원_boj_14503_로봇 청소기.java
<풀이>
이 로봇 청소기는 만들다 말았는지 왜 나보고 청소 로직 짜달라는거임 ㅡㅡ
첨에 BFS로 돌렸는데 안되서 DFS로 다시 풀었다.
문제에서 2번으로 가기, 1번으로 가기 일 때마다 재귀를 다시 돌면서 반복할 수 있게 구성하였음.
주어진 조건은 simulation 메서드 안에 주석으로 구현해두었음
알고하수는 20000
> 221124 안영원 백준 14503 로봇 청소기 풀이

- 221130/안영원_programmers_큰 수 만들기.java
조금 애를 먹었다.
큰 수를 만들려면 앞에서 부터 가장 큰 수를 찾고 그 수 다음에 또 제일 큰 수를 찾는 방식으로 전체 탐색을 진행해야한다.
예시가 1924인데 k가 2여서 2개를 제거해서 나오는 가장 큰 수가 94인데
일단 두 개를 제거해야하므로 192까지 탐색이 가능하다. 4를 먼저 탐색하면 뒤에 남은 수가 없기때문에 2개를 지우지 못함 !
그렇다면 탐색 범위가 전체 길이인 4에서 k를 뺀 idx가 2인 "2"까지로 제한해주어야해서 첫 번째 for문의 범위가 지정되었다.
그 다음으로는 192까지 탐색하면서 가장 큰 수인 9를 골라내고 idx를 체크한 후
9이후이면서 한 개는 이미 찾았으니 9뒤에 24까지 탐색이 가능해서 idx부터 k + i 포함한 위치까지 범위가 된다.
그래서 결과적으로 94를 찾아서 정답으로 리턴
완탐인데 범위 지정이 중요한 그런 문제였다.
---추가---
기본 구성이 String answer로 되어있어서 String으로 출력했는데 시간 초과가 나서
StringBuilder를 사용해서 해결하였다.
> 221130 안영원 프로그래머스 큰 수 만들기 풀이

- 221130/박동준_programmers_큰 수 만들기.py
1. 처음 숫자를 answer에 넣어준다.
2. for문을 통해 한 숫자씩 탐색을 한다.
3. 이때, 마지막의 숫자보다 더 큰 숫자가 나온다면, 다음 넣을 숫자보다 같거나 큰 숫자가 나올때까지 answer에 있는 문자열을 제거 해 준다.
4. 이외에는 문자열에 계속 더해준다.
5. break 가 되었을 때 k가 0이라면, 이후 더해지지 못한 문자열을 더해준다.
6. k가 0이 아니라면 점점 작아지는 숫자로 된 문자열이였기 때문에, 끝에서 k개를 제거 해 준다.
> 221130 박동준 프로그래머스 큰 수 만들기 풀이

- 221130/장예찬_programmers_큰 수 만들기.py
<풀이 과정>
1. 스택으로 푼다.
2. 숫자의 첫 글자를 가진 리스트를 초기화 한다.
3. 숫자의 순서는 바꿀 수 없으므로 리스트의 마지막 원소보다 새 수가 더 클 때 pop하고 k를 1씩 빼는 것을 반복한다.
4. 계속 num을 뒤에 추가한다.
5. 앞에 있는 숫자보다 크면 계속 교체되면서 최적으로 전체가 바뀔 것이다. k가 남는다면 k만큼 자른다.
6. 문자열을 합쳐서 출력한다.
> 221130 장예찬 프로그래머스 큰 수 만들기 풀이

- 221130/김광희_programmers_큰 수 만들기.java
( 문제 풀이 )
1. 0 ~ (number.length() - k) (return 해야할 문자 길이 수 만큼) 인덱스 사이에서 가장 큰 값을 구한다.
2. 제일 처음 index(탐색 시작점) 에서 (i+k) 인덱스 이하까지 가장 큰 숫자를 찾는다.
3. 가장 큰 값을 찾았다면 max 에 갱신 후 index를 찾은 숫자 다음 index 값으로 갱신
-> 아래 테스트 케이스 설명에 갱신해서 풀어나가는 그리디적 방법을 적어 둠.
4. 시작점 에서 (i+k)까지 탐색이 끝난 후 가장 큰 숫자 값을 StringBuilder에 누적
( 테스트 케이스 이해 설명 )
- 25843235 에서 4자리 => 맨 뒤 2,3,5를 제외한 숫자중에 가장 큰 수를 찾는다. 25843 ==> 8이다.
sb = "8" 오른쪽 인덱스 부터 다시 탐색을 한다. 
- 43235중에 맨뒤 2개를 제외하고 "432" 중 가장 큰 값을 찾는다. sb = "4" 오른쪽 인덱스 부터 다시 탐색을 한다.
- 3235 중에 맨뒤 1개를 제외하고 "323" 중 가장 큰 값을 찾는다. sb = "3" 오른쪽 인덱스 부터 다시 탐색을 한다.
- 235 중에 가장 큰 값을 찾는다 sb = "5" -> 마지막 자리의 큰 숫자를 찾는 과정
조합으로 풀려다 시간복잡도가 터질거 같아서 어떻게 시간을 감소 시킬지 생각하는대 오래 걸렸다 ...
> 221130 김광희 프로그래머스 큰 수 만들기 풀이

- 221205/강소현_programmers_문자열 나누기.java
<문제 풀이>
- 문제 조건대로 풀었습니다.
1. 첫번째 문자열 다음 문자열이 첫번째 문자열과 같으면 카운트 (first)
2. 첫번째 문자열 다음 문자열이 첫번째 문자열과 다르면 카운트 (second)
- 1, 2에서 구한 카운트가 같으면 초기화 후 다시 탐색 + 분해
- 분해 후, 마지막 한 글자만 남았을 경우도 체크
<br>
누가 first, second 변수명으로 뭐라했지만 바꾸지 않겠다.
> 221205 강소현 프로그래머스 문자열 나누기 풀이

- 221205/김광희_programmers_문자열 나누기.java
( 문제 풀이 )
1. 첫 글자 처음에 뽑고, 첫 글자는 무조건 -> 현재 단어와 같다라는 의미로 same_index 증가
2. now_word와 현재 문자 단어(s.charAt(i)) 가 같다면 same_index 증가
만약 같지 않다면 different_index 증가
-> 처음으로 두 횟수가 같아지는 순간 멈추고 라는 지문에 의해 
-> same_index와 different_index가 같다면 분해여부 상태가 true로 초기화로 맨 처음 (1)번 단계로 이동 
또한, 분해한 문자열 개수 증가
3. (1), (2) 번 과정이 끝나고 index가 문자열 끝인대, 분해 해야 할 문자가 남아있다면 분해할 문자열 개수 answer 증가.
> 221205 김광희 프로그래머스 문자열 나누기 풀이 

- 221205/장예찬_programmers_문자열 나누기.py
<풀이 과정>
1. 문자열 순회 방식으로 푼다.
2. one과 two가 같으면 temp를 curr로 바꾸어 주고 answer를 1 올린다.
3. 처음 시작부터 같은 시점이 생기므로 선입금을 해준다.
4. one과 two를 같은지 다른지로 올려주면서  끝까지 반복하면 answer가 정답이다.
> 221205 장예찬 프로그래머스 문자열 나누기 풀이

- 221208/박동준_programmers_짝지어 제거하기.py
1. 짝지어지는 값이 아니거나, 스택에 값이 없다면 비교군으로 넣기 위해 스택에 추가해줌
2. 스택의 마지막 값과 현재 반복문에서 나온 문자열이 같다면 스택의 마지막 값 제거
3. 아니라면 스택 추가
4. 다 끝난 후 스택에 값이 남아있다면 쌍을 못이뤘기 때문에 0 return
5. 아니면 쌍이 이루어 졌기 때문에 1 return
> 221208 박동준 프로그래머스 짝지어 제거하기 풀이

- 221207/장예찬_boj_1174.py
- 221208/장예찬_programmers_짝지어 제거하기.py
- 221212/장예찬_programmers_다리를 지나는 트럭.py
당일 참석하지 못했던 문제 풀이 올립니다.
A. 짝지어 제거하기
<풀이 과정>
1. 스택을 하나 선언한다.
2. 문자열을 순회한다.
3. 스택이 비어있지 않다면 마지막 원소와 현재 문자를 비교해서 같다면 pop, 다르다면 append를 반복한다.
4. 삼항연산자로 비어있으면 1 안 비어있으면 0을 출력하면 끝
--- 
B. 줄어드는 수
잘 안 풀려서 조합으로 풀기 쉽단 힌트 얻음
<풀이과정>
1. 조합으로 푼다.
2. 11자리까지 0부터 9까지의 숫자로 조합하는 경우를 모두 구한다.
3. 각 숫자가 하나씩 조합되면 정렬만 하면 항상 줄어드는 수가 될 수 있다.
4. 즉 같은 수가 없는 경우엔 모두 정렬되면 줄어드는 수이다.
5. 모든 조합을 구한 뒤 내림차순 정렬로 n의 인덱스 -1을 출력한다. 길이를 넘으면 -1을 출력한다.
___
C. 다리를 지나는 트럭
<풀이 과정>
1. 두 개의 큐를 이용해 푼다.
2. 다리는 정해진 무게 이하만 올라갈 수 있다.
3. 다리 길이만큼 0으로 초기화 후 하나를 popleft하고 무게가 허용하는 한 버스를 올리는 식으로 반복하여 다리의 길이가 0이 될때까지 반복하면 답이 도출된다.
> 221208 장예찬 프로그래머스 짝지어 제거하기 풀이 & 221207 장예찬 백준 1174 줄어드는 수 풀이 & 221212 장예찬 프로그래머스 다리를 지나는 트럭 풀이

- 221208/안영원_programmers_짝지어 제거하기.java
네.. 스택이네요
스택이 비었거나 스택의 최상위(peek)과 같지않을 때 push를 해주고
스택의 최상위(peek)과 같다면 pop을 해줍니다.
문자열을 전부 탐색한 후 스택이 비었다면 짝을 모두 찾은 것이므로 1을 반환하고
아니면 0을 반환합니다.
> 221208 안영원 프로그래머스 짝지어 제거하기 풀이

- 221212/강소현_programmers_다리를 지나는 트럭.java
<문제 풀이>
- truck, bridge Queue를 두어 무게를 비교
- truck Queue에는 트럭들을 순서대로 넣었고 bridge Queue에는 다리 길이만큼 트럭이 올라갈 수 있다는 조건을 고려하여 w개의 0을 초기값으로 넣고 무게를 비교했다.
- 무게 비교는 모든 트럭이 다리를 건넜을 때 끝난다.
> 221212 강소현 프로그래머스 다리를 지나는 트럭 풀이

- 221212/안영원_programmers_다리를 지나는 트럭.java
이전에 풀어봤던 거라 이전 풀이 말고 새로운게 생각이 안나네요.
그냥 풀이했던 흐름을 가지고 코드만 새로 구성했는데 만족스럽진 않음
큐자체가 다리가 되어서 푸는 구조
트럭이 지나갈수있으면 큐에 넣어주고 안되면 0을 대신 넣어줌
그래서 큐의 크기와 다리의 길이가 같아지면 하나씩 빼주는 방식
모든 트럭을 그런식으로 다리에 올려주면 반복문이 종료
다리에 트럭이 올라간 상태로 끝나기때문에 마지막에 올라간 트럭이 다 지나가고 난 다음이 최종시간이라
마지막에 그만큼 더해주는 코드가 하나 추가되어있음.
다른 사람들의 창의적인 풀이가 궁금한 문제이다.. 보러가야지
> 221212 안영원 프로그래머스 다리를 지나는 트럭 풀이

- 221212/박동준_programmers_다리를 지나는 트럭.py
1. 처음 다리 길이만큼의 0으로 채워진 stack 배열을 만들고,
2. 각 변경에 따른 현재 다리에 있는 트럭의 무게 합을 정해 놓습니다 (시간복잡도를 줄이기 위함)
3. while문의 종료조건은 초기에 주어진 트럭 배열의 값이 존재할 때 까지로 지정합니다.
4. 이후 한번의 반복과정에서 stack의 배열의 값을 뺌과 동시에 무게도 빼줍니다, 시간 cnt 는 1증가합니다.
5. 다음에 올 트럭의 무게가 현재 다리무게의 합과 합쳤을 때 다리가 버틸 수 있는 하중을 초과하지 않는다면 무게를 더해주고 스택에 값을 추가합니다. 그리고 원 배열의 0번째 인덱스 값을 제거합니다.
6. 아닐경우, stack에 0을 추가합니다.
종료가 되었을 때, 마지막 트럭이 다리에 올라갔기 때문에, cnt에 다리길이만큼 더해주면 원하는 값을 구할 수 있습니다.
> 221212 박동준 프로그래머스 다리를 지나는 트럭 풀이

- 221214/강소현_programmers_[1차] 캐시.java
<문제 풀이>
- 캐시 교체 알고리즘이 뭔지 몰라서 검색했다. 
- Queue로 풀이했고 캐시 크기에 따라 캐시 존재 유무를 파악해서 실행 시간을 측정해주면 된다.
> 221214 강소현 프로그래머스 [1차] 캐시 풀이

- 221214/장예찬_programmers_[1차] 캐시.py
<풀이 방식>
1. 캐시를 큐와 셋으로 관리한다.
2. 캐시가 셋에 존재하면 큐에서 제거 후 큐 마지막에 추가 O(n) 비용이 듬. 
3. 캐시 미스의 경우 O(1)의 방식으로 추가
4. 위 캐시 추가와 삭제에서 캐시 탐색시간은 O(1)임.
> 221214 장예찬 프로그래머스 [1차] 캐시 풀이

- 221214/박동준_programmers_[1차] 캐시.js
1. 들어온 순서대로 캐시사이즈가 차기전까지 넣어줌
2. 캐시사이즈를 초과하면 있는 단어있인지 찾음
3. 있는 단어라면 제거 후 리스트의 마지막에 넣어줌
4. 없는 단어라면 0번째 인덱스의 값을 제거하고, 새로운 값을 넣어줌
5. 끝
> 221214 박동준 프로그래머스 [1차] 캐시 풀이

- 221214/안영원_programmers_[1차] 캐시.java
LRU를 코드로 구현해보기는 첨인 것 같다.
캐시 크기만큼 도시이름들을 넣어두고 
만약 캐시에 해당 도시이름이 있다면 빠르게 불러올 수 있으므로 cache hit라서 1의 시간이 소요
없으면 cache miss가 되어 5의 시간이 소요되는게 기본틀이며 이를 바탕으로 코드를 구성하였다.
---
_ArrayList의 indexOf를 활용해보려고 ArrayList를 사용하긴 했는데 String이라 값을 제대로 확인하지 못해서 따로 확인하는 메서드를 추가하였다.
그래서 일반 배열 사용했어도 크게 상관은 없었을 듯._
---
ArrayList의 크기가 캐시사이즈보다 작으면 리스트의 제일 앞에 추가해주고
크다면 제일 뒤에 있는 도시이름을 제거하고 제일 앞에 추가해주면서 5를 추가한다.
만약 ArrayList 안에 이미 도시이름이 존재한다면 해당 도시이름을 제일 앞으로 이동시켜주며 1을 추가한다.
모든 도시이름을 다 탐색하였다면 캐시에 남은 것들은 다 cache miss 처리로 그 개수 * 5 만큼 시간을 추가해준다.
설명이 두서가 없긴한데 암튼 그렇다.
> 221214 안영원 프로그래머스 [1차] 캐시 풀이

- 221215/안영원_programmers_가장 가까운 같은 글자.java
동일한 알파벳이 언제 나왔는지를 확인하는 문제였다.
알파벳의 경우 26개이기 때문에 배열을 생성해서 관리하면 될 것이라고 생각하였다.
그래서 전체 알파벳이 등장한 위치를 기록하는 alphabet 배열을 생성해서 사용했다.
---
알파벳이 처음 등장했을 때는 -1을 출력해야하므로 -1로 전체를 채워두고 시작했고,
알파벳의 경우 -a를 해주면 알파벳의 위치에 해당하는 index를 받을 수 있기 때문에 이를 이용했다.
현재 curAlpha의 최근 등장 위치가 -1일 때는 등장한 적이 없기 때문에 -1를 채워주고
-1이 아니면 현재 위치 - 등장 위치를 해주었다.
그리고 현재 알파벳의 위치를 배열에 새로 갱신해주었다.
이를 반복하며 해결함 !
> 221215 안영원 프로그래머스 가장 가까운 같은 글자 풀이

- 221214/김광희_programmers_[1차] 캐시.java
( 문제 설명 ) 
- LRU: 가장 오랫동안 참조하지 않은 개체를 캐시에서 교체
( 문제 풀이 )
1. 먼저 cacheSize가 0이라면 무조건 MISS기 때문에 모든 시간이 +5초
2. 도시이름 길이 만큼 반복문을 도는대 먼저 도시 이름은 대문자로 변경하여 준다.
그 후, LinkedList 에 해당 도시이름이 포함(HIT)되어 있다면 해당 도시 이름을 제거하고, 새로 해당 도시 이름을 입력해 준다.
-> 그리고 HIT 시간 즉, answer에 +1 하기
3. 만약 해당 도시 이름이 포함되어 있지 않다면(MISS)
-> 먼저 캐시 사이즈와 LinkedList 사이즈가 같다면 캐시가 가득찼다는 의미로 가장 오래 남겨진 도시 이름을 제거하고
-> 새로 입력된 도시 이름을 추가 및 answer에 +5 하기
-> 캐시 사이즈가 가득 차 있지 않다면 새로운 도시 이름을 추가 및 answer에 +5 해주기
4. 총 실행시간 출력
< 추가적 2번째 방법 >
위와 비슷한 로직이지만 도시 이름이 포함되어 있는 경우 바로 도시 이름을 제거하는 것을 
if문 조건 -> if(cache.remove(city))로 좀더 시간 복잡도가 개선된 것 같다.
그리고 좀 더 명시적으로 하기 위해 addFirst() 함수로 새로 입력된 것들을 추가해 주고, 가장 오래된 것을 빼기 위해 pollLast()로 가장 마지막 도시 이름을 제거하는 함수도 이용하였다.
> 221214 김광희 프로그래머스 [1차] 캐시 풀이

- 221215/강소현_programmers_가장 가까운 같은 글자.java
<문제 풀이>
- 맨 첫 글자의 경우 자신의 앞에 같은 글자가 없음 → -1
- 비교하고자 하는 문자열 기준으로 앞을 탐색해서 같은 문자열이 있을 경우 인덱스 거리 계산
> 221216 강소현 프로그래머스 가장 가까운 같은 글자 풀이

- 221215/장예찬_programmers_가장 가까운 같은 글자.py
<풀이과정>
1. 딕셔너리로 푼다.
2. 문자열을 순회하여 딕셔너리에 없다면 해당 인덱스를 저장. answer에는 -1 추가
3. 딕셔너리에 있다면 해당 인덱스와 딕셔너리 값을 빼서 answer에 추가
4. answer 리턴.
> 221215 장예찬 프로그래머스 가장 가까운 같은 글자 풀이

- 221219/장예찬_boj_19583.py
<풀이 과정>
1. Set을 활용한다.
2. 두 개의 Set을 이용해 입장 시간에 맞는 경우에만 넣은 Set과 해당 Set에 존재해야만 넣는 Set을 준비한다.
3. 후자의 Set의 길이를 반환한다.
4. 문자열은 sys모듈의 readlines를 이용해 전체 문자열을 미리 받아 놓고 수행한다.
5. 시간을 숫자로 바꾸는 함수를 활용한다.
> 221219 장예찬 19583 백준 싸이버개강총회 풀이

- 221219/강소현_boj_19583_싸이버개강총회.java
<문제 풀이>
- 종료 조건 인텔리제이에선 오류 떠서 이걸로 30분 잡아 먹음
- 따로 시간이랑 분을 변경하지 않고 `replace(":", "")`를 제거 후에 숫자로 변경 (ex. 23:00 → 2300)
- HashSet 출석과 퇴실 2개를 나눠서 사용해서 출석도 했고 시간안에 퇴실도 했으면 출석 인증되게 구현
> 221219 강소현 19583 싸이버개강총회 풀이

- 221219/안영원_boj_19583_싸이버개강총회.java
무한정한 채팅을 받아내는 법만 알면 간단한 문제였던 것 같다.
어떻게 끝을 처리해야할지몰라 while ((temp = br.readLine) != null) 부분만 참조해서 사용했다.
시간은 ":"만 제거하면 크고 작음이 비교되기 때문에 ":"를 제거하고 int로 받아서 사용했다.
시작 전에 채팅을 친 사람들을 nameSet에 넣어놓고 종료 후에 채팅을 쳤다면 nameSet에 있는지 확인하고 출석하였으므로 1을 추가해주었다.
종료 후에 채팅을 여러 번 쳐서 카운팅이 여러 번 될 수 있기 때문에 확인한 사람은 Set에서 제거해주었다.
> 221219 안영원 19583 싸이버개강총회 풀이

- 221221/강소현_boj_9935_문자열 폭발.java
~~커밋명...날짜 그대로 복사해서..패키지명 지우고 다시 올림..ㅎㅎ~~
<문제 풀이>
- 문자열이 폭발 문자열을 포함하고 있는 경우 → 문자열 폭발
- 폭발 시키고 남은 문자열을 순서대로 이어붙여 새로운 문자열을 만듦
- 폭발은 폭발 문자열이 문자열에 없을 때까지 반복
> 221221 강소현 백준 9935 문자열 폭발 풀이

- 221221/김광희_boj_9935_문자열 폭발.java
( 문제 풀이 ) 
1. 스택을 활용하여 입력받은 문자열 맨 앞에서부터 하나씩 스택에 넣어준다.
2. 스택의 사이즈가 폭발 문자열 길이와 같다면 -> 폭발 문자열이 존재할 가능성이 있기때문에 
-> if문 안에서 스텍에 들어있는 문자와 폭발 문자열의 문자와 비교하여 "폭발 문자열이 포함되어 있는지, 없는지 " 여부를
isCheck 변수로 판단한다.
-> 만약 폭발 문자열이 포함되어 있다면 stack에서 폭발 문자열을 꺼내준다.
3. 모든 폭발이 끝나고 난 후 스텍에 남은 문자열을 sb에 누적해 준다.
4. 그 후 StringBuilder에 남아있는 문자가 없는 경우가 있다. 이때는 "FRULA"를 출력 
-> 남아 있는 문자가 있다면 그대로 출력
> 221221 김광희 백준 9935 문자열 폭발 풀이

- 221222/안영원_programmers_게임 맵 최단거리.java
최단거리를 찾기 위해서 BFS를 사용하는 간단한 문제
BFS의 경우 거리별로 순서대로 진행이 되기 때문에 가장 먼저 목적지에 도착한 횟수가 최소횟수가 됨.
그래서 목적지에 도착할 경우 바로 탐색을 종료하고 답을 출력
> 221222 안영원 프로그래머스 게임 맵 최단거리 풀이

- 221222/박동준_programmers_게임 맵 최단거리.py
단순 bfs 문제,
대신 방문 처리를 이전의 이동거리를 통해 구함
deque를 이용해 시간 최적화
> 221222 박동준 프로그래머스 게임 맵 최단거리 풀이

- 221222/강소현_programmers_게임 맵 최단거리.java
<문제 풀이>
그냥 간단한 BFS 문제였다. 목적지까지 가장 먼저 도착하는 횟수가 최단 거리이므로 목적지까지 도착하면 카운트한 횟수를 반환했다.
> 221222 강소현 프로그래머스 게임 맵 최단거리 풀이

- 221226/강소현_programmers_햄버거 만들기.java
<문제 풀이>
- 문자열로 풀이했는데 종료 조건을 정해도 시간초과가 나서 그냥 stack으로 다시 풀었습니다.
- pop하고자 하는 값이 1인지 먼저 조회(peek) && stack 사이즈가 햄버거를 만들 수 있는 크기일 때  : pop해서 1, 3, 2, 1 이란 값을 찾아나갔습니다.
- 만약 아니라면 stack은 마지막으로 들어간 값이 먼저 삭제되는 특징을 활용하여 마지막으로 나온 값부터 차례대로 다시 stack에 넣어줬습니다.
> 221226 강소현 프로그래머스 햄버거 만들기 풀이

- 221226/안영원_programmers_햄버거 만들기.java
저번에 풀이했던 문자열 폭발과 동일한 문제
주어진 N의 범위도 같아서 같은 풀이를 사용하면 되겠다고 생각해서 사용해서 풀이함
#272 문자열 폭발 풀이
---
앞에서부터 탐색하면서 햄버거를 만드는데 필요한 재료의 개수인 4이상일 때 앞에 있는 재료들이 "1231"인지 확인하고 맞다면 지워주고
answer를 1씩 더해주었음.
> 221226 안영원 프로그래머스 햄버거 만들기 풀이

- 221226/장예찬_programmers_햄버거 만들기.py
<풀이 과정>
1. 스택으로 푼다.
2. 스택에 요리 재료를 쌓고 마지막 4개와 레시피가 같은지 
비교한다.
3. 같으면 4번 pop하고 answer를 1 올린다.
> 221226 장예찬 프로그래머스 햄버거 만들기 풀이

- 221226/김광희_programmers_햄버거 만들기.java
( 문제 풀이 ) 
1. stack에 햄버거 재료를 넣는다.
2. 햄버거 재료가 4개 이상 쌓일경우 -> 재료 순서를 비교할 수 있으므로 조건문을 태운다.
->  빵 야채 고기 빵 으로 쌓인 햄버거 일 경우 -> 햄버거 개수 증가 및 사용된 햄버거 재료 제거
> 221226 김광희 프로그래머스 햄버거 만들기 풀이

- 221228/장예찬_boj_1303_전쟁 - 전투.py
<풀이과정>
1. DFS로 푼다.
2. 모든 W와 B를 리스트에 넣어놓고 DFS를 돌리면 된다.
3. visited를 활용해서 방문한 것은 넘어간다. 모든 전장의 원소들을 하나씩 그룹해서 카운팅하고 그 제곱을 정답에 더해가면 된다.
---
Class를 이용해서 dfs의 매개변수를 줄이는 것이 더욱 클린코드에 도움이 될 수 있다.
> 221228 장예찬 백준 1303 전쟁 - 전투 풀이

- 221228/안영원_boj_1303_전쟁 - 전투.java
간단한 BFS 탐색 문제
탐색을 통해 같은 병사끼리 뭉쳐있다면 얼마나 뭉쳐있는지 BFS를 통해 탐색하고
제곱을 해준다음 결과값에 반영해주었다.
뭉쳐있지 않다면 제곱하지않고 그냥 반영되게끔 해두었는데
1을 제곱해도 1이기 때문에 굳이 조건문을 나눌 필요는 없을 것 같다.
> 221228 안영원 백준 1303 전쟁 - 전투 풀이
