220727/강소현_boj_16174_점프왕 쩰리.java

1. DFS, BFS 둘 다 사용해서 풀었습니다.
2. 쩰리는 오른쪽, 아래로만 이동할 수 있으며 이동 할 때, 해당 위치의 값을 곱해 이동시켰습니다.

220727 강소현 백준 16174 점프왕 쩰리 풀이

---

220801/김광희_programmers_[1차] 뉴스 클러스터링.java

( 문제 풀이 )
- str1, str2를 모두 대문자로 형 변환 시켜준다.
-> 입력에서 대문자와 소문자의 차이는 무시한다, 즉 같은 원소로 취급한다 라고 언급이 되어있기 때문
- str1과 str2각각 다중 집합 원소를 만들어준다.
- 그 후, str2 다중 집합안에 str1의 집합원소가 포함되어 있는 것을 ( 교집합 리스트에 추가 ) 
-> str2 다중 집합에서 < str1 원소가 포함되어 있는 것은 제거 > 시켜준다. ( 나중에 합집합을 위해서 )
-> str1 다중 집합원소는 모두 합집합 리스트에 추가한다.
- str2에 남은 원소를 합집합 리스트에 추가한다.
- 교집합과, 합집합이 모두 0인경우는 1 * 65536으로 출력 처리
- 그렇지 않은 경우는 ( 교집합 / 합집합 ) * 65536 한 뒤 소수점 아래를 버린 정수 부분만을 출력하게 함

220801 김광희 프로그래머스 [1차] 뉴스 클러스터링 풀이

---

220803/김광희_programmers_모음사전.java

( 문제 풀이 )
1. DFS를 활용하여 단어 길이가 < 1이상 5 이하라고 제한 > 되어 있기 때문에 < 알파벳 AEIOU 배열을 이용하여 >
깊이는 1씩 증가하며 alpha 배열 인덱스를 중복 허용하여 사용하였음
ex) A 1
ex) AA 2
ex) AAAAA 5
ex) AAAAU 9
2. 만약 타겟이 아닌 찾을 단어 길이가 5를 초과하는 경우는 볼 필요도 없기 때문에 return ( 가지 치기 )
< 5를 초과하지 않는 경우만 > 몇 번째 단어인지 알기 위해 count 변수에 +1 씩 해줌.
3. 알파벳 모음들을 사용하여 찾을 target 단어와 같은 단어인 경우 boolean 타입 find 변수에 true 후
해당하는 단어를 사전에서 찾았으면 더 이상 찾을 필요 없기 때문에 재귀들을 종료 시켜 줌.

220803 김광희 프로그래머스 모음사전 풀이

---

220824/강소현_programmers_두 큐 합 같게 만들기.java

1. queue1 배열과 queue2 배열에 담긴 값 sum1, sum2 변수에 각각 합을 담는다. 이후 Queue q1, q2에 해당 배열 값을 담는다.
2. `sum1 < sum2`일 경우 q2 값을 poll() 해서 sum1에는 더해주고 sum2에는 빼준다. 이후 q1에 poll()한 값을 넣는다.
3. `sum1 > sum2`일 경우 q1 값을 poll() 해서 sum2에는 더해주고 sum1에는 빼준다. 이후 q2에 poll()한 값을 넣는다.
4. sum1, sum2를 long 타입으로 지정해야 테스트케이스 25~27에 오버플로우가 발생하지 않는다.
5. 해당 연산을 반복했을 때, 합이 같아지지 않으면 -1을 반환해야 한다. 이에 `queue1 배열 크기 * queue2 배열 크기`를 해주었더니 시간 초과가 났다. 이 부분은 내가 문제 제한사항을 간과했던 거 같다. 그래서 최대로 순환할 수 있는 횟수를 고려하여 queue1 배열 크기 * 4를 해주었다.

220824 강소현 프로그래머스 두 큐 합 같게 만들기 풀이

---

220824/김광희_programmers_두 큐 합 같게 만들기.java

/**
( 문제 풀이 )
주의 ! -> 문제에서 오버플로우 발생할 수 있다고 하여서 sum1, sum2 변수를 long 타입으로 잡았다.
1. q1, q2 각 큐에 queue1, queue2 원소를 넣고, 각 sum1, sum2에 queue1, queue2 원소 누적 합을 시킨다.
2. 두 배열의 원소 누적 합이 2로 나누었을 때 1인 경우 "똑같은 합을 만들 수 없기 때문"에 -1 을 리턴해 준다.
3. sum1 이 sum2 보다 클 경우 q1에서 원소 하나를 꺼낸 뒤 q2 제일 뒤에 넣어준다. 
그 후, sum1에는 q1에서 꺼낸 원소를 빼주고, sum2에는 q1에서 꺼낸 원소를 더해준다. 그 후 < 작업 횟수를 1 증가 >
sum2 가 sum1 보다 작을 경우도 위와 같은 과정을 해 준다.   
4. 각 큐의 원소합 즉, sum1과 sum2가 동일하다면 해당 작업 횟수를 return
5. 만약 어떤 방법으로 각 큐의 원소 합을 같게 만들 수 없는 경우, -1을 return
if (q1.isEmpty() || q2.isEmpty())break;
-> 작업을 해주어도 원소 합을 같게 만들 수 없을때 위 조건문으로 while문 탈출 조건을 주었더니 11번, 28번 테케 시간 초과 발생...
그래서 그냥 count == queue1.length * queue2.length 만큼 해보았고 안 되길래
count == (queue1.length * 숫자) -> '숫자' 부분에 1부터 1씩 올라가 보면서 넣어보았는대
count == (queue1.length * 4) -> 때 통과가 되었다... 원인은 아직 잘 …

220824 김광희 프로그래머스 두 큐 합 같게 만들기 풀이

---

220829/강소현_programmers_오픈채팅방.java

- 상태, 아이디, 닉네임을 받고 상태가 `Enter` , `Change` 일 경우에 아이디와 닉네임을 map에 담는다. 이는 `채팅방에서 나간 유저가 닉네임을 변경하는 등 잘못 된 입력은 주어지지 않는다.` 라는 조건 때문이다.
- 이후 다시 상태를 확인하여 map에 담긴 닉네임 + 상태(채팅방에 들어왔는지 나갔는지)를 list에 담는다.

220829 강소현 프로그래머스 오픈채팅방 풀이

---

220907/박동준_boj_13397_구간 나누기2.py

우선 왜 이분탐색으로 값을 찾아야 하는 이유에 대해서 생각 해 보았다.
bf 로 풀 경우, M 이하의 구간이 되는 모든 경우를 찾아야 한다 --> M의 값이 1< M < 5000 이기 때문에, 딱 봐도 많은 case가 생길 거라고 확신할 수 있다. 
그렇다면 우리는 구간을 어떻게 나눌까? 가 아니라 어떤값이 최소값이 될 수 있을까? 를 기준으로 역탐색을 실시해야한다.
1번째 case에서  3이라는 숫자를 사용하면, m=3일때 구간을 초과한다. 따라서 mid 값을 +1 해주고 시작점을 mid +1한 값으로 설정한다. 다시 중간점 으로부터 탐색을 반복하면서, 구간의 갯수가 초과가 되었을때는 end 값을 mid-1로 해주면 끝
어떻게 이분 탐색을 사용하고, 기준값, 구간 변경 조건의 값을 어떻게 설정하느냐에따라 복잡한 문제도 이진탐색으로 해결할 수 있음을 배웠다.

220907 박동준 백준 13397 구간 나누기 2 풀이

---

220915/Main_G3_1937_욕심쟁이판다.java

( 문제 풀이 )
1. 대나무 숲의 크기를 저장하는 2차원 배열과, 각 지점에서 갈 수 있는 "최대 거리를 저장"해 놓는 2차원 배열을 초기화 및 사용
2. [0][0] 부터 dfs 탐색을 돌리며, 처음 방문한 경우 해당 좌표는 1로 초기화 하고 시작 -> 처음 대나무 바로 먹기!
3. 만약 4방으로 이동한 방향(map[nr][nc]의 대나무 숲의 크기가, 이전 대나무 숲의 크기(prev) 보다 크다면 이동 하며
최대 거리를 저장하는 배열의 < 기존 값과, 새로 깊이 탐색을 한 값 중 > "더 큰 값으로 갱신"
4. 더 이상 "4방 탐색을 할 수 없는 경우" 재귀가 종료되고 나서 처음 탐색한 좌표에 저장된 최대 깊이 탐색한 거리를 return 하여
max 값을 갱신 하여, 해당 max 값을 출력하도록 해결.
( 예시 설명 ) 
9로 예시를 들면 상,하,좌,우 순인대 위로는 갈 수 없고 아래쪽 방향으로 더 큰 값이 있어 탐색 가능하다.
따라서 아래 쪽 방향으로 깊이 탐색을 시작한다. 9 -> 11 -> 15 즉 dp[0][1] 은 < 3이라는 거리 >가 저장
그 다음 오른쪽 방향으로 갈 수 있기 때문에 깊이 탐색을 시작. 9 -> 12 즉, < 2라는 거리 >가 나옴.
dp[0][1] 은 현재 3이라는 값인대 "오른쪽 방향" 으로 깊이 탐색을 한 경우는 2이기 때문에 [ dp 배열에 갱신할 필요가 없음  ]
dp[1][3] 은 4 -> 5 -> 11 -> 15로 총 4라는 거리가 나옴으로, 판다가 이동할 수 있는 칸의 수의 최댓 값이 된다.

220915 김광희 백준 1937 욕심쟁이 판다 풀이

---

220915/박동준_boj_1937_욕심쟁이판다.py

1. 일단 dfs 인것을 인지함.
2. 그런데 모든 좌표에 대해서 dfs를 실행시키는것을 알게됨 이때, 시간 복잡도가 증가하여 시간초과가 무조건 날것이라고 생각함. 
3. 첫번째 풀이로 가는 모든 경로에 대해서 count 값을 기존의 값과 비교하고  저장하는 가지치기를 시도함, recursion error 이후 수정하였으나 시간초과가 났음.
4. 시간 초과가 난 이유는 불필요한 탐색이 존재한다는 것이였음 그래서 이걸 오또카지오또카지 하고 있다가 해결책을 생각함
5. 경로에 대한 최댓값을 갱신해주는것은 좋았으나, 내가 짠 로직으로는 방문했던 배열을 계속 탐색하는 문제가 발생함.
6. dfs의 return 값을 제공하여, 끝점부터 값을 받아오게 하는 로직과, 해당 포인트에서 갈 수 있는 최대 거리를 저장하고, 이 지점에 대한 정보가 있다면 해당 지점의 값을 return함 그러면 다른곳에서 방문했을 때 + 1을 해주기만해도 해당 구간들 다 탐색할 필요가 없음.
7. 끝!

220915 박동준 백준 1937 욕심쟁이 판다 풀이

---

220922/김광희_programmers_후보키.java

( 문제 풀이 ) 
1. 컬럼에 대한 중복 조합을 활용하여 1개의 키 부터 ~컬럼 수 까지의 경우의 수를 구한다.
2. 해당 경우의 수 중 "후보키"로 사용될 컬럼 인덱스를 구한 뒤 해당 컬럼에서의 유일성을 판단하기 위해 HashSet을 활용
3. 유일성에 만족한다면 -> 최소성을 검증한다.
4. 최소성 까지 검증이 된다면 후보키 리스트(candidateKey)에 해당 "후보키"로 사용될 컬럼 인덱스 묶음 문자열을 저장.
5. 최종 후보키 리스트의 사이즈를 결과로 출력

220922 김광희 프로그래머스 후보키 풀이

---

220926/강소현_boj_1162_도로포장.java

1. 현재 위치 → 다음위치 : 도로를 포장하지 않고 최소 비용 탐색
2. 현재 위치 → 다음위치 : 도로를 포장하면서 최소 비용 탐색 (단, K개 이하만큼 도로 포장 가능할 때)
3. 43%에서 시간 초과가 났다. `if(graph[n.to][n.road] < n.cost) continue;` 조건이 없어서 시간 초과가 났었다. 현재 도시 최소 비용이 현재 최소 비용보다 적으면 탐색 할 필요가 없다.

220926 강소현 백준 1162 도로포장 풀이

---

220922/안영원_programmers_후보키.java
220926/안영원_boj_1162_도로포장.java

되게 열심히 풀어봤던 문제라 복습함
1번에서 N번까지 가는 최소 시간을 출력하는 문제인데,
추가적으로 도로포장이라는 조건이 주어져있다.
포장이 가능한 횟수는 K로 주어지고, 포장을 하게 되면 해당 도시를 잇는 도로를 통과하는 시간이 0이 된다.
그래서 기본 다익스트라에 추가적으로 포장횟수를 기록해야 한다.
원래 배열은 dijk[해당 도시까지 최솟값] 을 나타낸다고 하면
이번 문제에서는 dijk[해당 도시까지 최솟값][포장 횟수] 를 사용한 2차원 배열을 이용해준다.
또 큐에 넣을 때도 다음 도시로 갈 때 도로를 포장하거나 안 하는 경우 둘 다 가능한지 확인하고 가능하다면 큐에 넣어서 돌려준다.
그리고 핵심이 되는 부분은 BFS 방식으로 탐색을 진행하면서
현재 지점에 저장된 최소 시간이 현재 시간보다 적다면 굳이 탐색할 필요 없어서 continue로 넘어가 주는 것이 중요하다.
이걸 하지 않으면 시간 초과가 난다. 그래서 몇 번 실패했다.

220926 안영원 백준 1162 도로포장 풀이

---

220929/강소현_programmers_전력망을 둘로 나누기.java

- 탐색 할 때, 한 쪽만 탐색했습니다. 노드 카운트 시키고 `(n - ret) - ret` 해서 구했습니다.
- 다음 노드 탐색 할 때 `end`랑 일치하고 이미 방문했으면 끊어줬습니다.
- dfs로 바꿔보려고 했는데 어제 못 푼 문제가 생각나서 bfs로만 풀고 갑니다. 총총

220929 강소현 프로그래머스 전력망을 둘로 나누기 풀이

---

220929/박동준_programmers_전력망 둘로 나누기.py

간선을 하나씩 제거하고 이것들의 집합을 구하는 문제이다.
집합을 가장 쉽게 구하는 방법은 union, find를 이용해야겠다! 라고 생각하고 코드 작성을 시작했다.
오랜만에 풀게 된 union find 문제라서 실수 한 점은
union by rank를 이용하여 나온 par (= 부모의 정보) 가 있더라도 모든 구간이 통일되지 않는다는 점인데
즉, 마지막에 각 지점의 집합을 알기 위해서는 find 함수를 한번 더 호출해야 한다는 것이다.
그 외에는 이중 for 문을 통해 하나의 간선을 제외하고 union find를 수행하면 된다.

220929 박동준 프로그래머스 전력망 둘로 나누기 풀이

---

220929/김광희_programmers_전력망을 둘로 나누기.java

( 문제 풀이 )
1. graph에  양방향 그래프 정보를 입력 받아 셋팅해 준다.
2. bfs를 통해 v1을 기준으로 다음으로 가는 노드가 매개변수로 < 주어진 v2 송전탑 연결된 부분이 아니며 >, 
방문하지 않았을 경우 큐에 넣어준다 -> 그래야 v2 전선을 끊고 해당 v1 노드를 기준으로 송전탑 개수를 세어줄 수 있음
-> 즉, v1에서 v2로 가는 경우를 제거해준다는 의미이다.
3. 2번 과정을 모든 간선에 대하여 완전탐색을 하여
( 두 전력망이 가지고 있는 송전탑 개수의 차이(절대값)가 ) 가장 적게 나는 것을 return 시켜줌

220929 김광희 프로그래머스 전력망을 둘로 나누기 풀이

---

221026/안영원_boj_12764_싸지방에 간 준하.java

너무 까다로웠던 문제
총 3개의 우선순위큐를 활용했다.
1. waitQ -> 대기인원 : 시작 시간이 적은 사람부터 먼저 꺼내서 확인하기 위함
2. playerQ -> 이용인원 : 현재 싸지방을 이용 중인 사람
3. comQ -> 사용가능한 컴퓨터 : 사용 가능한 컴퓨터의 번호 (1 ~ 100000)
2개의 정렬 class를 활용
1. Person : 시작시간과 종료시간을 가지고 있으며 시작 시간 기준으로 정렬 -> waitQ에 활용
2. Player : 종료시간과 이용하고 있는 컴퓨터 번호를 가지고 있으며 종료 시간 기준으로 정렬 -> playerQ에 활용
---
<풀이 과정>
정렬된 대기인원을 사용해 시작 시간이 작은 인원부터 컴퓨터를 사용하게 해준다.
이 때 이미 이용 중인 인원이 있다면 현재 인원의 시작 시간보다 이용 중인 인원의 종료 시간이 더 빠른지 확인한다.
- 빠르다면 해당 인원은 종료 시키고 그 인원이 사용하던 컴퓨터의 번호를 comQ에 넣어준다.
- 아니라면 더 이상 탐색하지 않음(종료 시간으로 정렬되어서 추가로 탐색해도 현재 인원의 시작 시간보다 종료 시간이 더 늦음)
이 후 사용가능한 컴퓨터를 확인한다(comQ)
- 만약 사용가능한 컴퓨터가 있다면(누군가 사용하다 종료한 경우) 해당 컴퓨터를 현재 인원이 사용하게끔 해주고 used에 사용한 사람이 추가되었음을 표시
- 없다면 index(코드에서 max) 번호의 컴퓨터를 할당해준다. (가용할 컴퓨터 대수가 늘어나게됨)
대기인원이 없을 때까지 반복.
이후 used 배열이 0인 부분까지 탐색한다(0이면 그 이전까지 컴퓨터 대수가 필요하다는 …

221026 안영원 백준 12764 싸지방에 간 준하 풀이

---

221027/강소현_boj_1715_카드 정렬하기.java

<풀이>
- 작은 수부터 더해줘야 돼서 우선순위 큐 사용
- 두 개의 숫자를 뽑아야 하므로 while문 돌릴 때 pq.size() > 1

221027 강소현 백준 1715 카드 정렬하기 풀이

---

221031/안영원_programmers_스킬트리.java

주어진대로 구현하면 되는 문제
문제에서 주어진 skill_trees와 skill의 범위가 20, 26으로써 전체를 탐색해서 확인해도 시간상 문제가 없어 전체 탐색으로 코드를 구현
또한 skill_trees의 원소에 중복이 없기 때문에 구현이 더욱더 쉬웠다.
현재 유저의 스킬트리를 탐색하면서 선행스킬이 필요한 즉, skill 내부에 있는 스킬이 포함되어 있다면(checkInSkill 함수)
skill 내부의 첫번째 스킬과 유저가 찍은 스킬이 일치하는지 확인해준다. -> 선행스킬에 맞게끔 찍었는지
만약 다르다면 이전 선행스킬을 찍지않고 다음 스킬을 찍은 것이므로 X
같다면 다음 선행스킬을 탐색하게끔 idx를 증가시켜준다.
말로 설명이 쉽지않아 코드에 주석을 열심히 적었다...

221031 안영원 프로그래머스 스킬트리 풀이

---

221110/김광희_boj_1449_수리공 항승.java

( 문제 풀이 )
1. 물이 새는 곳의 위치를 저장 한 뒤 오름차순으로 정렬
2. 처음 위치에 테이프 길이 만큼 붙여준다.  -> 이 때 테이프 개수를 1로 셋팅, 이미 테이프를 처음 위치 물이 세는 곳의 위치에 붙여줬기 때문
3. 처음 테이프 위치를 붙인 곳 보다 더 큰 범위의 물이 세는 곳의 위치가 들어왔을경우, 
- 처음 테이프 위치 붙인 범위 값을 더 큰 범위의 물이 세는 곳의 위치에 테이프를 붙인 범위로 갱신을 시켜준다.
- 테이프의 개수를 증가시켜준다.

221110 김광희 백준 1449 수리공 항승 풀이

---

221114/안영원_boj_12869_뮤탈리스크.java

~~일단 실패한거 올려둡니다. 다시 풀면 여기에 업데이트 될 예정~~
성공했다 !!
실패한 풀이 
- scv 개수에 맞게 가능한 조합을 구성
- 해당 조합으로 데미지를 입혀서 scv 모두가 파괴된 경우를 찾음
- scv가 60 60 60 일 때 14회까지 도달하는데 시간초과가 남
성공한 풀이
- 실패한 것과 전체적인 풀이는 같지만 추가적으로 check 3차원 배열을 통해 이미 확인한 HP 조합인지 체크해주는 코드를 추가하였습니다.
- BFS로 탐색이 이루어지기 때문에 뒤쪽에 탐색되는 것은 횟수가 이미 최소가 아니여서 앞에서 확인을 했던 조합이라면 뒤에서 추가적으로 체크가 이루어지지 않게 check 배열을 사용했습니다.
- n이 2거나 1일 때는 3차원 배열의 뒷부분을 0으로 넣어서 방문을 확인할 수 있게 구성하였습니다.

221114 안영원 백준 12869 뮤탈리스크 풀이

---

221114/장예찬_boj_12869_뮤탈리스크.py
221116/장예찬_programmers_연속 부분 수열 합의 개수.py

<풀이과정>
1. dp로 푼다.
2. 3차원 배열의 인덱스들을 SCV 1번 2번 3번의 체력이라 생각함 즉 dp란 3차원  배열 dp[i][j][k]의 i, j, k는 각 SCV의 체력을 의미함
3. dp가 가지는 값은 해당 체력이 되기 위한 최소 카운팅 값임
4. 3중 for문을 이용해서 최대 체력에서부터 빼기 시작한다.
5.방문하기 전인 경우 혹은 새로운 체력 상태가 더 적은 카운팅으로 도착 가능하면 업데이트 함
6. 순회 완료 후 dp[0][0][0]를 출력
<풀이과정> 
1. 집합 자료구조로 푼다.
2. elements를 두 개 이어서 붙인다.
3. 일정 길이의 부분 수열을 모두 구해 집합에 넣는다.
4. 길이 출력
<풀이과정>
1. 집합 자료구조로 푼다.
2. 합을 구한 인덱스를 저장하는 [idx, 합] 를 원소로 갖는 리스트를 만든다.
3. 인덱스를 1씩 증가시키면서 기존의 합에서 바로 옆 인덱스의 원소를 더하면 길이가 늘어난 합이다.
4. 이를 elements의 길이 - 1만큼 반복하면 모든 경우가 구해진다.
5. 길이 출력
시간복잡도가 개선됨!

221114 장예찬 백준 12869 뮤탈리스크 풀이 & 221116 장예찬 프로그래머스 연속 부분 수열 합의 개수 풀이

---

221114/박동준_boj_12869_뮤탈리스크.py

실패함.
현재 접근법
1. heapq를 이용하여 제일 큰 수부터 9,3,1 순서로 빼게하고 count를 늘리는 방식으로 접근
2. 현재 1번 테케 빼고 맞아서 print를 통해 확인한 결과
3. 무조건 큰 순서대로 빼는것이 아님을 확인
4. 다시 접근할 필요가 있음.

221114 박동준 백준 12869 뮤탈리스크 풀이

---

221116/안영원_programmers_연속 부분 수열 합의 개수.java

원형 배열이기 때문에 끝자리에서 처음으로 이어지는 경우를 위해서 원래 배열의 2배만큼 생성하고 뒤에 원래 배열을 추가로 넣어준다.
길이가 1인 수열부터 elements의 길이인 수열까지 각 자리수에서 계산하여줌.
i가 수열의 길이를 나타내고
j는 시작점을 나타냄
j에서 i길이까지의 수열을 더하는 것은 stream을 활용한 방법을 검색을 통해 확인하여 사용함
원이라서 원래 배열 2배로 이어줘야하는 점이 이해가 잘안가서 오래걸림
이해하고 나서 코드 구현은 어렵지 않았음.

221116 안영원 프로그래머스 연속 부분 수열 합의 개수 풀이

---

221116/박동준_programmers_연속 부분 수열 합의 개수.py

제일 처음 list를 이용하여 결과를 가지는 arr에 값이 있는지 없는지 판별을 하려고 했음.
이 in으로 인한 시간복잡도가 올라간다는것을 인지하고
set으로 변경함
list의 경우 끝에 같은 배열을 더해주어, 범위 초과 없이 원하는 길이만큼 탐색할 수 있게함.
2중 for문에서
첫번째 for문의 i는 몇번째 idx 에서 시작하는지
두 번째 for문의 j는 총 보아야하는 길이를 뜻함
쭉 더해주면서 값을 set에 add 하면 중복된 값은 자동으로 제거

221116 박동준 프로그래머스 연속 부분 수열 합의 개수 풀이

---

221123/김광희_boj_9466_텀 프로젝트.java

( 문제 이해하기 위해 적어봄 )
순환이 발생하면 탐색을 종료한다. 
ex) 4 -> 7 -> 6 -> 4 
또한 1번학생 기준 탐색 1->3->3 을 탐색했는대 
2번 학생을 기준으로 원래는 2->1->3->3 탐색을 해야하지만
2->1 까지만 가도, 이전에 1->3->3 을 이미 팀인지 아닌지 체크 했으니 < 탐색할 필요 없다. > -> 시간을 줄일 수 있음
( 문제 풀이 )
1. 1번 학생 번호 부터~ n번 학생 까지 dfs 탐색 시작
2. 현재 학생 번호는 방문 체크 후, 해당 학생 번호가 가르키는 < 다음 학생 번호를 방문 >하지 않았다면 해당 학생 번호로 dfs 탐색
해당 학생 번호를 방문하고, 해당 학생 번호로 "해당 학생이 선택하는 사람으로 계속 탐색"을 하지 않았다면
팀 편성 완료 인원 증가
-> 여기서 또, 현재 학생 번호가 다음 학생 번호와 같지않을때 까지 팀 편성 완료 인원 증가시켜 준다
이유 : cycle (순환) 이 될때까지 반복 -> 서로를 가르키고 있는게 하나의 팀이 되기 때문.
[ 결론 ]
1. 혼자 팀을 선택한 사람을 선택한 학생은 팀을 이룰 수 없다.
2. 팀을 이루기 위해선 cycle(순환)이 되어야 한다.

221123 김광희 백준 9466 텀 프로젝트 풀이

---

221205/ 안영원_programmers_명예의 전당 (1).java

기존 문자열 나누기는 풀었던 문제라서 다른거 풀었습니다. [문자열 나누기 풀이보기](https://toload.tistory.com/entry/JAVA-Programmers-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%82%98%EB%88%84%EA%B8%B0)
---
오늘꺼 풀이
k명의 가수가 명예의 전당에 오를 수 있음.
k명의 가수는 점수별로 정하기 때문에 k명이 쌓일 때까지 k일동안은 누구나 명예의 전당에 오르고 그 이후부터는 점수가 낮은 사람은 명예의 전당에서 탈락함.
매일마다 명예의 전당 최하점을 찾아 해당 값을 리턴해주어야함.
간단하게 우선순위큐를 이용해서 구현
우선순위큐의 사이즈가 k보다 작으면 계속 넣어주고 크다면 넣은다음 하나를 빼줌으로써 점수가 낮은 사람을 탈락시킴.
우선순위큐의 peek을 이용해서 가장 점수가 낮은 사람을 매일 확인함.

221205 안영원 프로그래머스 명예의 전당 (1) 풀이

---

221219/김광희_boj_19583.java

( 문제 설명 )
이런 문제를 해결하기 위해서, 다음과 같이 출석부를 관리하기로 결심했다.
개강총회를 시작하기 전에, < 학회원의 입장 확인 여부 >를 확인한다. 
- 학회원의 입장 여부는 개강총회가 < 시작한 시간 이전 >에 대화를 한 적이 있는 학회원의 닉네임을 "보고 체크"한다. 
- 개강총회를 < 시작하자마자  > 채팅 기록을 남긴 학회원도 제 시간에 입장이 확인된 것으로 간주한다.
- 개강총회를 끝내고 나서, 스트리밍을 끝낼 때까지 학회원의 "퇴장 확인 여부"를 확인한다. 
학회원의 퇴장 여부는 개강총회가 끝나고 스트리밍이 끝날 때까지 대화를 한 적이 있는 학회원의 닉네임을 보고 체크한다. 
개강총회가 끝나자마자 채팅 기록을 남겼거나, 개강총회 스트리밍이 끝나자마자 채팅 기록을 남긴 학회원도 제 시간에 퇴장이 확인된 것으로 간주한다.  
( 문제풀이 )
1. 문제 설명 대로 개강총회가 < 시작한 시간 이전 및 시작하자마자> 대화를 한 적이 있는 학회원이 있다면 start라는 HashSet에 학회원의 닉네임을 저장
2. 개강총회 끝낸 시간 보단 크거나 같고, < 개강총회 스트리밍 끝낸 시간 > 보단 작거나 같을 경우 해당 학회원은 퇴장이 학인된 것으로 간주하기 위해 end 라는 HashSet에 저장
3. 시작 시간에 출첵하였고, 퇴장 확인 여부 채팅 기록이 있다면 결과 수 answer 증가

221219 김광희 19583 싸이버개강총회 풀이

---

221221/안영원_boj_9935_문자열 폭발.java

문자열 폭발인데 문자 폭발로 문제를 풀이해서 다시 푸느라 시간이 좀 걸렸습니다.
웬지 2%에서 진행이 안되더라..
N의 최대가 100만이라 N^2으로 풀이하면 시간초과라서 한 번 탐색으로 풀이되는 방법을 고민하다가 StringBuilder를 이용
기존 문자열을 앞에서 부터 탐색하면서 StringBuilder에 추가해주고 StringBuilder 크기가 폭발 문자열과 같거나 크다면 이전 문자열을 확인하며 폭발 문자열인지 확인.
폭발 문자열이 맞다면 제거해주고 아니라면 쭉 진행하는 방식.
VS Code에서는 sb.isEmpty()가 먹혔는데 백준에선 안되서 length() == 0 으로 대체함.
아마 자바 8에서는 없는 것인가봄.

221221 안영원 백준 9935 문자열 폭발 풀이

---

221222/김광희_programmers_게임 맵 최단거리.java

( 문제 풀이 ) 
1. 단순 DFS/BFS 문제이다. 
2. 그냥 0,0 부터 상대팀 진영 오른쪽 대각선 끝 즉 maps[maps.length - 1][maps[0].length - 1]
까지 가장 적은 칸으로 이동가능한 칸의 개수를 return
-> 단, 벽(1) 이 아니거나, maps 공간 밖이 아닌경우 방문 처리 및 칸의 개수 증가 시켜줌.

221222 김광희 프로그래머스 게임 맵 최단거리 풀이

---

221228/김광희_boj_1303_전쟁 - 전투.java

( 문제풀이)
1. 좌표에 방문하지 않았을 경우 dfs를 탐색한다.
dfs의 매개변수는 행, 열, 해당 좌표의 병사들의 옷색을 넘겨준다
-> 해당 좌표의 병사들의 옷색과 같고, 해당 좌표에 방문하지 않았을 경우 count 증가와, 방문처리 및 dfs 깊이 탐색을 추가로 해준다.
2. dfs 탐색이 끝나고 해당 좌표의 색깔이 B인지, W인지에 따라 count의 ^2을 색깔에 맞는 합의 변수에 저장한다.

221228 김광희 백준 1303 전쟁 - 전투 풀이
